/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sparsejson.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sparsejson.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ;
typedef struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g;
typedef struct tySequence__zHcNN5cfKaXD6nyF1OJcyA tySequence__zHcNN5cfKaXD6nyF1OJcyA;
typedef struct tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg {
  RootObj Sup;
	NI bufpos;
	NimStringDesc* buf;
	tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg;
typedef NU8 tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw;
typedef NU8 tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA;
struct tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ {
  tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg Sup;
	NimStringDesc* a;
	tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg tok;
	tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw kind;
	tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA err;
	tySequence__zHcNN5cfKaXD6nyF1OJcyA* state;
	NimStringDesc* filename;
	NIM_BOOL rawStringLiterals;
};
typedef NU8 tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ;
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
struct tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g {
  tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g Sup;
};
typedef NimStringDesc* tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
typedef NimStringDesc* tyArray__q1pZD9bFRXyM1Mq6hPHTd2A[14];
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__zHcNN5cfKaXD6nyF1OJcyA {
  TGenericSeq Sup;
  tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ data[SEQ_DECL_SIZE];
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence__zHcNN5cfKaXD6nyF1OJcyA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_u144)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input_p1, NI bufLen_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars_p3);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ_p0, NI len_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsejson_u405)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_u91)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_u105)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, parseNumber__pureZparsejson_u443)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s_p0, NIM_CHAR c_p1);
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest_p0, NI addlen_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1873)(NimStringDesc* s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg, parseString__pureZparsejson_u287)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16__pureZparsejson_u273)(NCSTRING buf_p0, NI* pos_p1);
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_u1)(NIM_CHAR c_p0, NI* x_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, parseName__pureZparsejson_u506)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a_p0, NimStringDesc* b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1767)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tyRef__kcGPrQSHvV8Y89b4HGzfICQ)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected__pureZparsejson_u269)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0, NimStringDesc* e_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr_p0, NimStringDesc** a_p1, NI a_p1Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_u8)(NI x_p0);
static N_INLINE(NI, getLine__pureZparsejson_u235)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
static N_INLINE(NI, getColumn__pureZparsejson_u232)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_u163)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space_p0);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg, getTok__pureZparsejson_u522)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_u691)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, NimStringDesc* msg_p1);
extern TNimType NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_;
N_LIB_PRIVATE TNimType NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTItokkind__7uWPm2TEolRM1uqyBZh9asg_;
N_LIB_PRIVATE TNimType NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_;
N_LIB_PRIVATE TNimType NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_;
N_LIB_PRIVATE TNimType NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_;
N_LIB_PRIVATE TNimType NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__nIinruGrC8EPIfjL3PuTvA_15 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_26, "0.", 2);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__nIinruGrC8EPIfjL3PuTvA_34 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
0x20, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_71, "null", 4);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_72, "true", 4);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_73, "false", 5);
extern TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
N_LIB_PRIVATE TNimType NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_;
N_LIB_PRIVATE TNimType NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_75, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_76, " expected", 9);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_77, "invalid token", 13);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_78, "EOF", 3);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_79, "string literal", 14);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_80, "int literal", 11);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_81, "float literal", 13);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_82, "{", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_83, "}", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_84, "[", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_85, "]", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_86, ":", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_87, ",", 1);
N_LIB_PRIVATE NIM_CONST tyArray__q1pZD9bFRXyM1Mq6hPHTd2A tokToStr__pureZparsejson_u78 = {((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_77),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_78),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_79),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_80),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_81),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_72),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_73),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_71),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_82),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_83),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_84),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_85),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_86),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_87)}
;
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
static N_NIMCALL(void, Marker_tySequence__zHcNN5cfKaXD6nyF1OJcyA)(void* p, NI op) {
	tySequence__zHcNN5cfKaXD6nyF1OJcyA* a;
	NI T1_;
	a = (tySequence__zHcNN5cfKaXD6nyF1OJcyA*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsejson_u79)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0, tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input_p1, NimStringDesc* filename_p2, NIM_BOOL rawStringLiterals_p3) {
	open__pureZlexbase_u144(&my_p0->Sup, input_p1, ((NI)8192), TM__nIinruGrC8EPIfjL3PuTvA_15);
	unsureAsgnRef((void**) (&(*my_p0).filename), copyString(filename_p2));
	unsureAsgnRef((void**) (&(*my_p0).state), (tySequence__zHcNN5cfKaXD6nyF1OJcyA*) newSeq((&NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_), 1));
	(*my_p0).state->data[0] = ((tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ)1);
	(*my_p0).kind = ((tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw)0);
	unsureAsgnRef((void**) (&(*my_p0).a), ((NimStringDesc*) NIM_NIL));
	(*my_p0).rawStringLiterals = rawStringLiterals_p3;
}
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsejson_u405)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	NI pos;
	pos = (*my_p0).Sup.bufpos;
	{
		while (1) {
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			switch (((NU8)((*my_p0).Sup.buf->data[pos]))) {
			case 47:
			{
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_16;
					NI TM__nIinruGrC8EPIfjL3PuTvA_17;
					if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_16)) { raiseOverflow(); 					};
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_16) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_16) >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_16),((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 					}
					if (!((NU8)((*my_p0).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_16)]) == (NU8)(47))) goto LA6_;
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_17)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_17);
					{
						while (1) {
							if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 							}
							switch (((NU8)((*my_p0).Sup.buf->data[pos]))) {
							case 0:
							{
								goto LA8;
							}
							break;
							case 13:
							{
								pos = handleCR__pureZlexbase_u91(&my_p0->Sup, pos);
								goto LA8;
							}
							break;
							case 10:
							{
								pos = handleLF__pureZlexbase_u105(&my_p0->Sup, pos);
								goto LA8;
							}
							break;
							default:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_18;
								if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_18)) { raiseOverflow(); 								};
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_18);
							}
							break;
							}
						}
					} LA8: ;
				}
				goto LA4_;
LA6_: ;
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_19;
					NI TM__nIinruGrC8EPIfjL3PuTvA_20;
					if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_19)) { raiseOverflow(); 					};
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_19) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_19) >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_19),((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 					}
					if (!((NU8)((*my_p0).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_19)]) == (NU8)(42))) goto LA15_;
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_20)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_20);
					{
						while (1) {
							if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 							}
							switch (((NU8)((*my_p0).Sup.buf->data[pos]))) {
							case 0:
							{
								(*my_p0).err = ((tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA)8);
								goto LA17;
							}
							break;
							case 13:
							{
								pos = handleCR__pureZlexbase_u91(&my_p0->Sup, pos);
							}
							break;
							case 10:
							{
								pos = handleLF__pureZlexbase_u105(&my_p0->Sup, pos);
							}
							break;
							case 42:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_21;
								if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_21)) { raiseOverflow(); 								};
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_21);
								{
									NI TM__nIinruGrC8EPIfjL3PuTvA_22;
									if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 									}
									if (!((NU8)((*my_p0).Sup.buf->data[pos]) == (NU8)(47))) goto LA25_;
									if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_22)) { raiseOverflow(); 									};
									pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_22);
									goto LA17;
								}
LA25_: ;
							}
							break;
							default:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_23;
								if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_23)) { raiseOverflow(); 								};
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_23);
							}
							break;
							}
						}
					} LA17: ;
				}
				goto LA4_;
LA15_: ;
				{
					goto LA1;
				}
LA4_: ;
			}
			break;
			case 32:
			case 9:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_24;
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_24)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_24);
			}
			break;
			case 13:
			{
				pos = handleCR__pureZlexbase_u91(&my_p0->Sup, pos);
			}
			break;
			case 10:
			{
				pos = handleLF__pureZlexbase_u105(&my_p0->Sup, pos);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*my_p0).Sup.bufpos = pos;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1) {
	{
		if (!!((src_p1 == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_u1759(((void*) ((&(*dest_p0).data[(*dest_p0).Sup.len]))), ((void*) ((*src_p1).data)), ((NI) ((NI)((*src_p1).Sup.len + ((NI)1)))));
		(*dest_p0).Sup.len += (*src_p1).Sup.len;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, parseNumber__pureZparsejson_u443)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	NI pos;
	pos = (*my_p0).Sup.bufpos;
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_25;
		if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 		}
		if (!((NU8)((*my_p0).Sup.buf->data[pos]) == (NU8)(45))) goto LA3_;
		unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 45));
		if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_25)) { raiseOverflow(); 		};
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_25);
	}
LA3_: ;
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_27;
		if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 		}
		if (!((NU8)((*my_p0).Sup.buf->data[pos]) == (NU8)(46))) goto LA7_;
		unsureAsgnRef((void**) (&(*my_p0).a), resizeString((*my_p0).a, 2));
appendString((*my_p0).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_26));
		if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_27)) { raiseOverflow(); 		};
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_27);
	}
	goto LA5_;
LA7_: ;
	{
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_28;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				if (!(((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA11;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_28)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_28);
			} LA11: ;
		}
		{
			NI TM__nIinruGrC8EPIfjL3PuTvA_29;
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			if (!((NU8)((*my_p0).Sup.buf->data[pos]) == (NU8)(46))) goto LA14_;
			unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 46));
			if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_29)) { raiseOverflow(); 			};
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_29);
		}
LA14_: ;
	}
LA5_: ;
	{
		while (1) {
			NI TM__nIinruGrC8EPIfjL3PuTvA_30;
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			if (!(((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA17;
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
			if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_30)) { raiseOverflow(); 			};
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_30);
		} LA17: ;
	}
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_31;
		if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 		}
		if (!(((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(69)) || ((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(101)))) goto LA20_;
		if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 		}
		unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
		if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_31)) { raiseOverflow(); 		};
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_31);
		{
			NI TM__nIinruGrC8EPIfjL3PuTvA_32;
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			if (!(((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(43)) || ((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(45)))) goto LA24_;
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
			if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_32)) { raiseOverflow(); 			};
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_32);
		}
LA24_: ;
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_33;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				if (!(((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA27;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_33)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_33);
			} LA27: ;
		}
	}
LA20_: ;
	(*my_p0).Sup.bufpos = pos;
}
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_u1)(NIM_CHAR c_p0, NI* x_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = NIM_TRUE;
	switch (((NU8)(c_p0))) {
	case 48 ... 57:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_47;
		if (nimSubInt(((NU8)(c_p0)), ((NI)48), &TM__nIinruGrC8EPIfjL3PuTvA_47)) { raiseOverflow(); 		};
		(*x_p1) = (NI)((NI)((NU64)((*x_p1)) << (NU64)(((NI)4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_47));
	}
	break;
	case 97 ... 102:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_48;
		NI TM__nIinruGrC8EPIfjL3PuTvA_49;
		if (nimSubInt(((NU8)(c_p0)), ((NI)97), &TM__nIinruGrC8EPIfjL3PuTvA_48)) { raiseOverflow(); 		};
		if (nimAddInt((NI)(TM__nIinruGrC8EPIfjL3PuTvA_48), ((NI)10), &TM__nIinruGrC8EPIfjL3PuTvA_49)) { raiseOverflow(); 		};
		(*x_p1) = (NI)((NI)((NU64)((*x_p1)) << (NU64)(((NI)4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_49));
	}
	break;
	case 65 ... 70:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_50;
		NI TM__nIinruGrC8EPIfjL3PuTvA_51;
		if (nimSubInt(((NU8)(c_p0)), ((NI)65), &TM__nIinruGrC8EPIfjL3PuTvA_50)) { raiseOverflow(); 		};
		if (nimAddInt((NI)(TM__nIinruGrC8EPIfjL3PuTvA_50), ((NI)10), &TM__nIinruGrC8EPIfjL3PuTvA_51)) { raiseOverflow(); 		};
		(*x_p1) = (NI)((NI)((NU64)((*x_p1)) << (NU64)(((NI)4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_51));
	}
	break;
	default:
	{
		result = NIM_FALSE;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16__pureZparsejson_u273)(NCSTRING buf_p0, NI* pos_p1) {
	NI result;
{	result = (NI)0;
	result = ((NI)0);
	{
		NI _;
		NI res;
		_ = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_53;
				if (!(res <= ((NI)3))) goto LA3;
				_ = res;
				{
					NIM_BOOL T6_;
					NI TM__nIinruGrC8EPIfjL3PuTvA_52;
					T6_ = (NIM_BOOL)0;
					T6_ = handleHexChar__stdZprivateZdecode95helpers_u1(buf_p0[(*pos_p1)], (&result));
					if (!T6_) goto LA7_;
					if (nimAddInt((*pos_p1), ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_52)) { raiseOverflow(); 					};
					(*pos_p1) = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_52);
				}
				goto LA4_;
LA7_: ;
				{
					result = ((NI)-1);
					goto BeforeRet_;
				}
LA4_: ;
				if (nimAddInt(res, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_53)) { raiseOverflow(); 				};
				res = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_53);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s_p0 == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s_p0).Sup.len == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
LA5_: ;
	{
		result = ((NCSTRING) ((*s_p0).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg, parseString__pureZparsejson_u287)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg result;
	NI pos;
	NI TM__nIinruGrC8EPIfjL3PuTvA_35;
	result = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
	result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)2);
	if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_35)) { raiseOverflow(); 	};
	pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_35);
	{
		if (!(*my_p0).rawStringLiterals) goto LA3_;
		unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 34));
	}
LA3_: ;
	{
		while (1) {
			if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 			}
			switch (((NU8)((*my_p0).Sup.buf->data[pos]))) {
			case 0:
			{
				(*my_p0).err = ((tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA)7);
				result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0);
				goto LA5;
			}
			break;
			case 34:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_36;
				{
					if (!(*my_p0).rawStringLiterals) goto LA11_;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 34));
				}
LA11_: ;
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_36)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_36);
				goto LA5;
			}
			break;
			case 92:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_37;
				{
					if (!(*my_p0).rawStringLiterals) goto LA16_;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 92));
				}
LA16_: ;
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_37)) { raiseOverflow(); 				};
				if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_37) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_37) >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_37),((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				switch (((NU8)((*my_p0).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_37)]))) {
				case 92:
				case 34:
				case 39:
				case 47:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_38;
					NI TM__nIinruGrC8EPIfjL3PuTvA_39;
					if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_38)) { raiseOverflow(); 					};
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_38) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_38) >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_38),((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 					}
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_38)]));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_39)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_39);
				}
				break;
				case 98:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_40;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 8));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_40)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_40);
				}
				break;
				case 102:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_41;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 12));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_41)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_41);
				}
				break;
				case 110:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_42;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 10));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_42)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_42);
				}
				break;
				case 114:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_43;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 13));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_43)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_43);
				}
				break;
				case 116:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_44;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 9));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_44)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_44);
				}
				break;
				case 118:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_45;
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 11));
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_45)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_45);
				}
				break;
				case 117:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_46;
					NI pos2;
					NI r;
					{
						if (!(*my_p0).rawStringLiterals) goto LA28_;
						unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 117));
					}
LA28_: ;
					if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_46)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_46);
					pos2 = pos;
					r = parseEscapedUTF16__pureZparsejson_u273(nimToCStringConv((*my_p0).Sup.buf), (&pos));
					{
						if (!(r < ((NI)0))) goto LA32_;
						(*my_p0).err = ((tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA)1);
						goto LA5;
					}
LA32_: ;
					{
						NI TM__nIinruGrC8EPIfjL3PuTvA_55;
						NI s;
						if (!((NI)(r & ((NI)64512)) == ((NI)55296))) goto LA36_;
						{
							NIM_BOOL T40_;
							NI TM__nIinruGrC8EPIfjL3PuTvA_54;
							T40_ = (NIM_BOOL)0;
							if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 							}
							T40_ = !(((NU8)((*my_p0).Sup.buf->data[pos]) == (NU8)(92)));
							if (T40_) goto LA41_;
							if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_54)) { raiseOverflow(); 							};
							if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_54) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_54) >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_54),((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 							}
							T40_ = !(((NU8)((*my_p0).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_54)]) == (NU8)(117)));
LA41_: ;
							if (!T40_) goto LA42_;
							(*my_p0).err = ((tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA)1);
							goto LA5;
						}
LA42_: ;
						if (nimAddInt(pos, ((NI)2), &TM__nIinruGrC8EPIfjL3PuTvA_55)) { raiseOverflow(); 						};
						pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_55);
						s = parseEscapedUTF16__pureZparsejson_u273(nimToCStringConv((*my_p0).Sup.buf), (&pos));
						{
							NIM_BOOL T46_;
							NI TM__nIinruGrC8EPIfjL3PuTvA_56;
							NI TM__nIinruGrC8EPIfjL3PuTvA_57;
							NI TM__nIinruGrC8EPIfjL3PuTvA_58;
							T46_ = (NIM_BOOL)0;
							T46_ = ((NI)(s & ((NI)64512)) == ((NI)56320));
							if (!(T46_)) goto LA47_;
							T46_ = (((NI)0) < s);
LA47_: ;
							if (!T46_) goto LA48_;
							if (nimSubInt(r, ((NI)55296), &TM__nIinruGrC8EPIfjL3PuTvA_56)) { raiseOverflow(); 							};
							if (nimSubInt(s, ((NI)56320), &TM__nIinruGrC8EPIfjL3PuTvA_57)) { raiseOverflow(); 							};
							if (nimAddInt(((NI)65536), (NI)((NI)((NU64)((NI)(TM__nIinruGrC8EPIfjL3PuTvA_56)) << (NU64)(((NI)10))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_57)), &TM__nIinruGrC8EPIfjL3PuTvA_58)) { raiseOverflow(); 							};
							r = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_58);
						}
						goto LA44_;
LA48_: ;
						{
							(*my_p0).err = ((tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA)1);
							goto LA5;
						}
LA44_: ;
					}
LA36_: ;
					{
						NI length;
						NI TM__nIinruGrC8EPIfjL3PuTvA_59;
						if (!(*my_p0).rawStringLiterals) goto LA53_;
						if (nimSubInt(pos, pos2, &TM__nIinruGrC8EPIfjL3PuTvA_59)) { raiseOverflow(); 						};
						length = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_59);
						{
							NI i;
							NI res;
							i = (NI)0;
							res = ((NI)1);
							{
								while (1) {
									NI TM__nIinruGrC8EPIfjL3PuTvA_61;
									if (!(res <= length)) goto LA57;
									i = res;
									{
										NI TM__nIinruGrC8EPIfjL3PuTvA_60;
										if (pos2 < 0 || pos2 >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos2,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 										}
										if (!(((NU8)((*my_p0).Sup.buf->data[pos2])) >= ((NU8)(48)) && ((NU8)((*my_p0).Sup.buf->data[pos2])) <= ((NU8)(57)) || ((NU8)((*my_p0).Sup.buf->data[pos2])) >= ((NU8)(65)) && ((NU8)((*my_p0).Sup.buf->data[pos2])) <= ((NU8)(70)) || ((NU8)((*my_p0).Sup.buf->data[pos2])) >= ((NU8)(97)) && ((NU8)((*my_p0).Sup.buf->data[pos2])) <= ((NU8)(102)))) goto LA60_;
										if (pos2 < 0 || pos2 >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos2,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 										}
										unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos2]));
										if (nimAddInt(pos2, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_60)) { raiseOverflow(); 										};
										pos2 = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_60);
									}
									goto LA58_;
LA60_: ;
									{
										goto LA55;
									}
LA58_: ;
									if (nimAddInt(res, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_61)) { raiseOverflow(); 									};
									res = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_61);
								} LA57: ;
							}
						} LA55: ;
					}
					goto LA51_;
LA53_: ;
					{
						NimStringDesc* T64_;
						if ((r) < ((NI32)(-2147483647 -1)) || (r) > ((NI32)2147483647)){ raiseRangeErrorI(r, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); 						}
						T64_ = NIM_NIL;
						T64_ = nuctoUTF8(((NI32) (r)));
						unsureAsgnRef((void**) (&(*my_p0).a), resizeString((*my_p0).a, (T64_ ? T64_->Sup.len : 0) + 0));
appendString((*my_p0).a, T64_);
					}
LA51_: ;
				}
				break;
				default:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_62;
					if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 					}
					unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
					if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_62)) { raiseOverflow(); 					};
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_62);
				}
				break;
				}
			}
			break;
			case 13:
			{
				pos = handleCR__pureZlexbase_u91(&my_p0->Sup, pos);
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 13));
			}
			break;
			case 10:
			{
				pos = handleLF__pureZlexbase_u105(&my_p0->Sup, pos);
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, 10));
			}
			break;
			default:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_63;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_63)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_63);
			}
			break;
			}
		}
	} LA5: ;
	(*my_p0).Sup.bufpos = pos;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, parseName__pureZparsejson_u506)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	NI pos;
	pos = (*my_p0).Sup.bufpos;
	{
		if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 		}
		if (!(((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(97)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(122)) || ((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(65)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(90)) || ((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(95)))) goto LA3_;
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_70;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				if (!(((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(97)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(122)) || ((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(65)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(90)) || ((NU8)((*my_p0).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my_p0).Sup.buf->data[pos])) <= ((NU8)(57)) || ((NU8)((*my_p0).Sup.buf->data[pos])) == ((NU8)(95)))) goto LA6;
				if (pos < 0 || pos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 				}
				unsureAsgnRef((void**) (&(*my_p0).a), addChar((*my_p0).a, (*my_p0).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_70)) { raiseOverflow(); 				};
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_70);
			} LA6: ;
		}
	}
LA3_: ;
	(*my_p0).Sup.bufpos = pos;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = (int)0;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1767)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a_p0, NimStringDesc* b_p1) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a_p0 ? a_p0->Sup.len : 0);
	blen = (b_p1 ? b_p1->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1767(((void*) ((&a_p0->data[((NI)0)]))), ((void*) ((&b_p1->data[((NI)0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg, getTok__pureZparsejson_u522)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg result;
	result = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
	unsureAsgnRef((void**) (&(*my_p0).a), setLengthStr((*my_p0).a, ((NI)0)));
	skip__pureZparsejson_u405(my_p0);
	if ((*my_p0).Sup.bufpos < 0 || (*my_p0).Sup.bufpos >= ((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)){ raiseIndexError2((*my_p0).Sup.bufpos,((*my_p0).Sup.buf ? (*my_p0).Sup.buf->Sup.len : 0)-1); 	}
	switch (((NU8)((*my_p0).Sup.buf->data[(*my_p0).Sup.bufpos]))) {
	case 45:
	case 46:
	case 48 ... 57:
	{
		parseNumber__pureZparsejson_u443(my_p0);
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = contains__pureZstrutils_u1873((*my_p0).a, TM__nIinruGrC8EPIfjL3PuTvA_34);
			if (!T4_) goto LA5_;
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)4);
		}
		goto LA2_;
LA5_: ;
		{
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)3);
		}
LA2_: ;
	}
	break;
	case 34:
	{
		result = parseString__pureZparsejson_u287(my_p0);
	}
	break;
	case 91:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_64;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_64)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_64);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)10);
	}
	break;
	case 123:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_65;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_65)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_65);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)8);
	}
	break;
	case 93:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_66;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_66)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_66);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)11);
	}
	break;
	case 125:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_67;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_67)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_67);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)9);
	}
	break;
	case 44:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_68;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_68)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_68);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)13);
	}
	break;
	case 58:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_69;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_69)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_69);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)12);
	}
	break;
	case 0:
	{
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)1);
	}
	break;
	case 97 ... 122:
	case 65 ... 90:
	case 95:
	{
		parseName__pureZparsejson_u506(my_p0);
		if (eqStrings((*my_p0).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_71))) goto LA17_;
		if (eqStrings((*my_p0).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_72))) goto LA18_;
		if (eqStrings((*my_p0).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_73))) goto LA19_;
		goto LA20_;
		LA17_: ;
		{
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)7);
		}
		goto LA21_;
		LA18_: ;
		{
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)5);
		}
		goto LA21_;
		LA19_: ;
		{
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)6);
		}
		goto LA21_;
		LA20_: ;
		{
			result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0);
		}
LA21_: ;
	}
	break;
	default:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_74;
		if (nimAddInt((*my_p0).Sup.bufpos, ((NI)1), &TM__nIinruGrC8EPIfjL3PuTvA_74)) { raiseOverflow(); 		};
		(*my_p0).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_74);
		result = ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0);
	}
	break;
	}
	(*my_p0).tok = result;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__kcGPrQSHvV8Y89b4HGzfICQ)(void* p, NI op) {
	tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g* a;
	a = (tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI, getLine__pureZparsejson_u235)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	NI result;
	result = (NI)0;
	result = (*my_p0).Sup.lineNumber;
	return result;
}
static N_INLINE(NI, getColumn__pureZparsejson_u232)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	NI result;
	result = (NI)0;
	result = getColNumber__pureZlexbase_u163((&(*my_p0).Sup), (*my_p0).Sup.bufpos);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected__pureZparsejson_u269)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0, NimStringDesc* e_p1) {
	NimStringDesc* result;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	NimStringDesc* T4_;
	result = NIM_NIL;
	nimZeroMem((void*)T1_, sizeof(tyArray__sMpvt1sOxOJ3LFGulnbeMQ));
	T1_[0] = copyString((*my_p0).filename);
	T2_ = (NI)0;
	T2_ = getLine__pureZparsejson_u235(my_p0);
	T1_[1] = dollar___systemZdollars_u8(T2_);
	T3_ = (NI)0;
	T3_ = getColumn__pureZparsejson_u232(my_p0);
	T1_[2] = dollar___systemZdollars_u8(T3_);
	T4_ = NIM_NIL;
	T4_ = rawNewString((e_p1 ? e_p1->Sup.len : 0) + 9);
appendString(T4_, e_p1);
appendString(T4_, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_76));
	T1_[3] = T4_;
	result = nsuFormatOpenArray(((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_75), T1_, 4);
	return result;
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_u691)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, NimStringDesc* msg_p1) {
	tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g*) newObj((&NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_), sizeof(tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_);
	(*T1_).Sup.Sup.Sup.name = "JsonParsingError";
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), errorMsgExpected__pureZparsejson_u269(p_p0, msg_p1));
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "JsonParsingError", "raiseParseErr", "parsejson.nim", 518);
}
N_LIB_PRIVATE N_NIMCALL(void, eat__pureZparsejson_u731)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg tok_p1) {
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T5_;
		if (!((*p_p0).tok == tok_p1)) goto LA3_;
		T5_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T5_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T5_);
	}
	goto LA1_;
LA3_: ;
	{
		raiseParseErr__pureZparsejson_u691((&(*p_p0)), tokToStr__pureZparsejson_u78[(tok_p1)- 0]);
	}
LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsparsejsondotnim_DatInit000)(void) {
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_2_7[7];
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_3_14[14];
NI TM__nIinruGrC8EPIfjL3PuTvA_5;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_4[14] = {
"tkError", 
"tkEof", 
"tkString", 
"tkInt", 
"tkFloat", 
"tkTrue", 
"tkFalse", 
"tkNull", 
"tkCurlyLe", 
"tkCurlyRi", 
"tkBracketLe", 
"tkBracketRi", 
"tkColon", 
"tkComma"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_6_12[12];
NI TM__nIinruGrC8EPIfjL3PuTvA_8;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_7[12] = {
"jsonError", 
"jsonEof", 
"jsonString", 
"jsonInt", 
"jsonFloat", 
"jsonTrue", 
"jsonFalse", 
"jsonNull", 
"jsonObjectStart", 
"jsonObjectEnd", 
"jsonArrayStart", 
"jsonArrayEnd"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_9_11[11];
NI TM__nIinruGrC8EPIfjL3PuTvA_11;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_10[11] = {
"errNone", 
"errInvalidToken", 
"errStringExpected", 
"errColonExpected", 
"errCommaExpected", 
"errBracketRiExpected", 
"errCurlyRiExpected", 
"errQuoteExpected", 
"errEOC_Expected", 
"errEofExpected", 
"errExprExpected"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_12_8[8];
NI TM__nIinruGrC8EPIfjL3PuTvA_14;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_13[8] = {
"stateEof", 
"stateStart", 
"stateObject", 
"stateArray", 
"stateExpectArrayComma", 
"stateExpectObjectComma", 
"stateExpectColon", 
"stateExpectValue"};
static TNimNode TM__nIinruGrC8EPIfjL3PuTvA_0[58];
NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_.size = sizeof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ);
NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_.align = NIM_ALIGNOF(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ);
NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_.kind = 17;
NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_.base = (&NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_);
TM__nIinruGrC8EPIfjL3PuTvA_2_7[0] = &TM__nIinruGrC8EPIfjL3PuTvA_0[1];
TM__nIinruGrC8EPIfjL3PuTvA_0[1].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[1].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, a);
TM__nIinruGrC8EPIfjL3PuTvA_0[1].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__nIinruGrC8EPIfjL3PuTvA_0[1].name = "a";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[1] = &TM__nIinruGrC8EPIfjL3PuTvA_0[2];
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.size = sizeof(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg);
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.align = NIM_ALIGNOF(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg);
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.kind = 14;
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.base = 0;
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_5 = 0; TM__nIinruGrC8EPIfjL3PuTvA_5 < 14; TM__nIinruGrC8EPIfjL3PuTvA_5++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].offset = TM__nIinruGrC8EPIfjL3PuTvA_5;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].name = TM__nIinruGrC8EPIfjL3PuTvA_4[TM__nIinruGrC8EPIfjL3PuTvA_5];
TM__nIinruGrC8EPIfjL3PuTvA_3_14[TM__nIinruGrC8EPIfjL3PuTvA_5] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[17].len = 14; TM__nIinruGrC8EPIfjL3PuTvA_0[17].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[17].sons = &TM__nIinruGrC8EPIfjL3PuTvA_3_14[0];
NTItokkind__7uWPm2TEolRM1uqyBZh9asg_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[17];
TM__nIinruGrC8EPIfjL3PuTvA_0[2].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[2].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, tok);
TM__nIinruGrC8EPIfjL3PuTvA_0[2].typ = (&NTItokkind__7uWPm2TEolRM1uqyBZh9asg_);
TM__nIinruGrC8EPIfjL3PuTvA_0[2].name = "tok";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[2] = &TM__nIinruGrC8EPIfjL3PuTvA_0[18];
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.size = sizeof(tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw);
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.align = NIM_ALIGNOF(tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw);
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.kind = 14;
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.base = 0;
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_8 = 0; TM__nIinruGrC8EPIfjL3PuTvA_8 < 12; TM__nIinruGrC8EPIfjL3PuTvA_8++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].offset = TM__nIinruGrC8EPIfjL3PuTvA_8;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].name = TM__nIinruGrC8EPIfjL3PuTvA_7[TM__nIinruGrC8EPIfjL3PuTvA_8];
TM__nIinruGrC8EPIfjL3PuTvA_6_12[TM__nIinruGrC8EPIfjL3PuTvA_8] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[31].len = 12; TM__nIinruGrC8EPIfjL3PuTvA_0[31].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[31].sons = &TM__nIinruGrC8EPIfjL3PuTvA_6_12[0];
NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[31];
TM__nIinruGrC8EPIfjL3PuTvA_0[18].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[18].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, kind);
TM__nIinruGrC8EPIfjL3PuTvA_0[18].typ = (&NTIjsoneventkind__Z0yUls5TNirubOjTqye8Cw_);
TM__nIinruGrC8EPIfjL3PuTvA_0[18].name = "kind";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[3] = &TM__nIinruGrC8EPIfjL3PuTvA_0[32];
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.size = sizeof(tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA);
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.align = NIM_ALIGNOF(tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA);
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.kind = 14;
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.base = 0;
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_11 = 0; TM__nIinruGrC8EPIfjL3PuTvA_11 < 11; TM__nIinruGrC8EPIfjL3PuTvA_11++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].offset = TM__nIinruGrC8EPIfjL3PuTvA_11;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].name = TM__nIinruGrC8EPIfjL3PuTvA_10[TM__nIinruGrC8EPIfjL3PuTvA_11];
TM__nIinruGrC8EPIfjL3PuTvA_9_11[TM__nIinruGrC8EPIfjL3PuTvA_11] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[44].len = 11; TM__nIinruGrC8EPIfjL3PuTvA_0[44].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[44].sons = &TM__nIinruGrC8EPIfjL3PuTvA_9_11[0];
NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[44];
TM__nIinruGrC8EPIfjL3PuTvA_0[32].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[32].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, err);
TM__nIinruGrC8EPIfjL3PuTvA_0[32].typ = (&NTIjsonerror__TwbebOZrZoT9bkViQJkLnlA_);
TM__nIinruGrC8EPIfjL3PuTvA_0[32].name = "err";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[4] = &TM__nIinruGrC8EPIfjL3PuTvA_0[45];
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.size = sizeof(tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ);
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.align = NIM_ALIGNOF(tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ);
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.kind = 14;
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.base = 0;
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_14 = 0; TM__nIinruGrC8EPIfjL3PuTvA_14 < 8; TM__nIinruGrC8EPIfjL3PuTvA_14++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].offset = TM__nIinruGrC8EPIfjL3PuTvA_14;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].name = TM__nIinruGrC8EPIfjL3PuTvA_13[TM__nIinruGrC8EPIfjL3PuTvA_14];
TM__nIinruGrC8EPIfjL3PuTvA_12_8[TM__nIinruGrC8EPIfjL3PuTvA_14] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[54].len = 8; TM__nIinruGrC8EPIfjL3PuTvA_0[54].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[54].sons = &TM__nIinruGrC8EPIfjL3PuTvA_12_8[0];
NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[54];
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.size = sizeof(tySequence__zHcNN5cfKaXD6nyF1OJcyA*);
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.align = NIM_ALIGNOF(tySequence__zHcNN5cfKaXD6nyF1OJcyA*);
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.kind = 24;
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.base = (&NTIparserstate__ZjF3gjthbAdBlIANg3rGAQ_);
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.flags = 2;
NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_.marker = Marker_tySequence__zHcNN5cfKaXD6nyF1OJcyA;
TM__nIinruGrC8EPIfjL3PuTvA_0[45].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[45].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, state);
TM__nIinruGrC8EPIfjL3PuTvA_0[45].typ = (&NTIseqLparserstateT__zHcNN5cfKaXD6nyF1OJcyA_);
TM__nIinruGrC8EPIfjL3PuTvA_0[45].name = "state";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[5] = &TM__nIinruGrC8EPIfjL3PuTvA_0[55];
TM__nIinruGrC8EPIfjL3PuTvA_0[55].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[55].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, filename);
TM__nIinruGrC8EPIfjL3PuTvA_0[55].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__nIinruGrC8EPIfjL3PuTvA_0[55].name = "filename";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[6] = &TM__nIinruGrC8EPIfjL3PuTvA_0[56];
TM__nIinruGrC8EPIfjL3PuTvA_0[56].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[56].offset = offsetof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ, rawStringLiterals);
TM__nIinruGrC8EPIfjL3PuTvA_0[56].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__nIinruGrC8EPIfjL3PuTvA_0[56].name = "rawStringLiterals";
TM__nIinruGrC8EPIfjL3PuTvA_0[0].len = 7; TM__nIinruGrC8EPIfjL3PuTvA_0[0].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[0].sons = &TM__nIinruGrC8EPIfjL3PuTvA_2_7[0];
NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[0];
NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_.size = sizeof(tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g);
NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_.align = NIM_ALIGNOF(tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g);
NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_.kind = 17;
NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_.base = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
TM__nIinruGrC8EPIfjL3PuTvA_0[57].len = 0; TM__nIinruGrC8EPIfjL3PuTvA_0[57].kind = 2;
NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[57];
NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_.size = sizeof(tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g*);
NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_.align = NIM_ALIGNOF(tyObject_JsonParsingError__Gif6MC6XqT1zppIkieVG6g*);
NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_.kind = 22;
NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_.base = (&NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_);
NTIrefjsonparsingerror__kcGPrQSHvV8Y89b4HGzfICQ_.marker = Marker_tyRef__kcGPrQSHvV8Y89b4HGzfICQ;
}

