/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@smath.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@smath.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u222)(NI x_p0) {
	NI result;
	result = (NI)0;
	result = (NI)(x_p0 - ((NI)1));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)32))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)16))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)8))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)4))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)2))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)1))));
	result += (NI)(((NI)1) + (x_p0 <= ((NI)0)));
	return result;
}
