/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@shashes.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@shashes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, murmurHash__pureZhashes_u194)(NU8* x_p0, NI x_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NU32, rotl32__pureZhashes_u182)(NU32 x_p0, NI r_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == ((NI)(IL64(-9223372036854775807) - IL64(1))));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == ((NI)-1));
LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA5_: ;
	{
		(*res_p2) = (NI)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(NU32, rotl32__pureZhashes_u182)(NU32 x_p0, NI r_p1) {
	NU32 result;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_5;
	result = (NU32)0;
	if (nimSubInt(((NI)32), r_p1, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_5)) { raiseOverflow(); 	};
	result = (NU32)((NU32)((NU64)(x_p0) << (NU64)(r_p1)) | (NU32)((NU32)(x_p0) >> (NU64)((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, murmurHash__pureZhashes_u194)(NU8* x_p0, NI x_p0Len_0) {
	NI result;
	NI size;
	NI stepSize;
	NI n;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_2;
	NU32 h1;
	NI i;
	NU32 k1_2;
	NI rem;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_6;
{	result = (NI)0;
	size = x_p0Len_0;
	stepSize = ((NI)4);
	if (stepSize == 0){ raiseDivByZero(); 	}
	if (nimDivInt(size, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_2)) { raiseOverflow(); 	};
	n = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_2);
	h1 = (NU32)0;
	i = ((NI)0);
	{
		while (1) {
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_3;
			NU32 k1;
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_4;
			if (nimMulInt(n, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_3)) { raiseOverflow(); 			};
			if (!(i < (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_3))) goto LA2;
			k1 = (NU32)0;
			if (i < 0 || i >= x_p0Len_0){ raiseIndexError2(i,x_p0Len_0-1); 			}
			k1 = (*((NU32*) ((&x_p0[i]))));
			if (nimAddInt(i, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_4)) { raiseOverflow(); 			};
			i = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_4);
			k1 = (NU32)((NU32)(k1) * (NU32)(((NU32)IL64(3432918353))));
			k1 = rotl32__pureZhashes_u182(k1, ((NI)15));
			k1 = (NU32)((NU32)(k1) * (NU32)(((NU32)461845907)));
			h1 = (NU32)(h1 ^ k1);
			h1 = rotl32__pureZhashes_u182(h1, ((NI)13));
			h1 = (NU32)((NU32)((NU32)((NU32)(h1) * (NU32)(((NU32)5)))) + (NU32)(((NU32)IL64(3864292196))));
		} LA2: ;
	}
	k1_2 = (NU32)0;
	if (stepSize == 0){ raiseDivByZero(); 	}
	if (nimModInt(size, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_6)) { raiseOverflow(); 	};
	rem = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_6);
	{
		while (1) {
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_7;
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_8;
			if (!(((NI)0) < rem)) goto LA4;
			if (nimSubInt(rem, ((NI)1), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_7)) { raiseOverflow(); 			};
			rem = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_7);
			if (nimAddInt(i, rem, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_8)) { raiseOverflow(); 			};
			if ((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8) < 0 || (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8) >= x_p0Len_0){ raiseIndexError2((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8),x_p0Len_0-1); 			}
			k1_2 = (NU32)((NU32)((NU64)(k1_2) << (NU64)(((NI)8))) | ((NU32) (x_p0[(NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8)])));
		} LA4: ;
	}
	k1_2 = (NU32)((NU32)(k1_2) * (NU32)(((NU32)IL64(3432918353))));
	k1_2 = rotl32__pureZhashes_u182(k1_2, ((NI)15));
	k1_2 = (NU32)((NU32)(k1_2) * (NU32)(((NU32)461845907)));
	h1 = (NU32)(h1 ^ k1_2);
	h1 = (NU32)(h1 ^ ((NU32) (size)));
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU64)(((NI)16))));
	h1 = (NU32)((NU32)(h1) * (NU32)(((NU32)IL64(2246822507))));
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU64)(((NI)13))));
	h1 = (NU32)((NU32)(h1) * (NU32)(((NU32)IL64(3266489909))));
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU64)(((NI)16))));
	result = ((NI) (h1));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u283)(NimStringDesc* x_p0) {
	NI result;
	result = (NI)0;
	if (((x_p0 ? x_p0->Sup.len : 0)-1)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= (x_p0 ? x_p0->Sup.len : 0) || ((x_p0 ? x_p0->Sup.len : 0)-1) < 0 || ((x_p0 ? x_p0->Sup.len : 0)-1) >= (x_p0 ? x_p0->Sup.len : 0))){ raiseIndexError4(((NI)0), ((x_p0 ? x_p0->Sup.len : 0)-1), (x_p0 ? x_p0->Sup.len : 0)); 	}
	result = murmurHash__pureZhashes_u194(((x_p0) ? ((NU8*)x_p0->data+(((NI)0))) : NIM_NIL), (((x_p0 ? x_p0->Sup.len : 0)-1))-(((NI)0))+1);
	return result;
}
