/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sparseutils.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sparseutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u327)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseFloat)(NIM_CHAR* s_p0, NI s_p0Len_0, NF* number_p1);
N_NIMCALL(NI, nimParseBiggestFloat)(NIM_CHAR* s_p0, NI s_p0Len_0, NF* number_p1);
extern TNimType NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_;
extern TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
STRING_LITERAL(TM__vI9aZNKIcImom6dDyKXW1ZA_8, "Parsed integer outside of valid range", 37);
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u6026(p_p0);
	decRef__system_u6071(T1_);
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void) {
	tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*) newObj((&NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_), sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vI9aZNKIcImom6dDyKXW1ZA_8));
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "integerOutOfRangeError", "parseutils.nim", 421);
}
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u327)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1) {
	NI result;
	NI64 sign;
	NI i;
	result = (NI)0;
	sign = IL64(-1);
	i = ((NI)0);
	{
		if (!(i < s_p0Len_0)) goto LA3_;
		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;
			if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 			}
			if (!((NU8)(s_p0[i]) == (NU8)(43))) goto LA7_;
			if (nimAddInt(i, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); 			};
			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2);
		}
		goto LA5_;
LA7_: ;
		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
			if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 			}
			if (!((NU8)(s_p0[i]) == (NU8)(45))) goto LA10_;
			if (nimAddInt(i, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); 			};
			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3);
			sign = IL64(1);
		}
		goto LA5_;
LA10_: ;
LA5_: ;
	}
LA3_: ;
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = (i < s_p0Len_0);
		if (!(T14_)) goto LA15_;
		if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 		}
		T14_ = (((NU8)(s_p0[i])) >= ((NU8)(48)) && ((NU8)(s_p0[i])) <= ((NU8)(57)));
LA15_: ;
		if (!T14_) goto LA16_;
		(*b_p1) = IL64(0);
		{
			while (1) {
				NIM_BOOL T20_;
				NI c;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_9;
				T20_ = (NIM_BOOL)0;
				T20_ = (i < s_p0Len_0);
				if (!(T20_)) goto LA21_;
				if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 				}
				T20_ = (((NU8)(s_p0[i])) >= ((NU8)(48)) && ((NU8)(s_p0[i])) <= ((NU8)(57)));
LA21_: ;
				if (!T20_) goto LA19;
				if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 				}
				if (nimSubInt(((NU8)(s_p0[i])), ((NI)48), &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); 				};
				c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4);
				{
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_5;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_6;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_7;
					if (nimAddInt64((IL64(-9223372036854775807) - IL64(1)), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); 					};
					if (!((NI64)((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_5) / IL64(10)) <= (*b_p1))) goto LA24_;
					if (nimMulInt64((*b_p1), IL64(10), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); 					};
					if (nimSubInt64((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_6), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); 					};
					(*b_p1) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_7);
				}
				goto LA22_;
LA24_: ;
				{
					integerOutOfRangeError__pureZparseutils_u325();
				}
LA22_: ;
				if (nimAddInt(i, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_9)) { raiseOverflow(); 				};
				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_9);
				{
					while (1) {
						NIM_BOOL T29_;
						NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;
						T29_ = (NIM_BOOL)0;
						T29_ = (i < s_p0Len_0);
						if (!(T29_)) goto LA30_;
						if (i < 0 || i >= s_p0Len_0){ raiseIndexError2(i,s_p0Len_0-1); 						}
						T29_ = ((NU8)(s_p0[i]) == (NU8)(95));
LA30_: ;
						if (!T29_) goto LA28;
						if (nimAddInt(i, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); 						};
						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10);
					} LA28: ;
				}
			} LA19: ;
		}
		{
			NIM_BOOL T33_;
			T33_ = (NIM_BOOL)0;
			T33_ = (sign == IL64(-1));
			if (!(T33_)) goto LA34_;
			T33_ = ((*b_p1) == (IL64(-9223372036854775807) - IL64(1)));
LA34_: ;
			if (!T33_) goto LA35_;
			integerOutOfRangeError__pureZparseutils_u325();
		}
		goto LA31_;
LA35_: ;
		{
			NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_11;
			if (nimMulInt64((*b_p1), sign, &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); 			};
			(*b_p1) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_11);
			result = i;
		}
LA31_: ;
	}
LA16_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1) {
	NI result;
	NI64 res;
	result = (NI)0;
	res = IL64(0);
	result = rawParseInt__pureZparseutils_u327(s_p0, s_p0Len_0, (&res));
	{
		if (!!((result == ((NI)0)))) goto LA3_;
		(*number_p1) = res;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseBiggestInt__pureZparseutils_u894)(NimStringDesc* s_p0, NI64* number_p1, NI start_p2) {
	NI result;
	result = (NI)0;
	if (((s_p0 ? s_p0->Sup.len : 0)-1)-start_p2 != -1 && (start_p2 < 0 || start_p2 >= (s_p0 ? s_p0->Sup.len : 0) || ((s_p0 ? s_p0->Sup.len : 0)-1) < 0 || ((s_p0 ? s_p0->Sup.len : 0)-1) >= (s_p0 ? s_p0->Sup.len : 0))){ raiseIndexError4(start_p2, ((s_p0 ? s_p0->Sup.len : 0)-1), (s_p0 ? s_p0->Sup.len : 0)); 	}
	result = npuParseBiggestInt(((s_p0) ? ((NIM_CHAR*)s_p0->data+(start_p2)) : NIM_NIL), (((s_p0 ? s_p0->Sup.len : 0)-1))-(start_p2)+1, number_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseFloat)(NIM_CHAR* s_p0, NI s_p0Len_0, NF* number_p1) {
	NI result;
	NF bf;
	result = (NI)0;
	bf = 0.0;
	result = nimParseBiggestFloat(s_p0, s_p0Len_0, (&bf));
	{
		if (!!((result == ((NI)0)))) goto LA3_;
		(*number_p1) = bf;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u924)(NimStringDesc* s_p0, NF* number_p1, NI start_p2) {
	NI result;
	result = (NI)0;
	if (((s_p0 ? s_p0->Sup.len : 0)-1)-start_p2 != -1 && (start_p2 < 0 || start_p2 >= (s_p0 ? s_p0->Sup.len : 0) || ((s_p0 ? s_p0->Sup.len : 0)-1) < 0 || ((s_p0 ? s_p0->Sup.len : 0)-1) >= (s_p0 ? s_p0->Sup.len : 0))){ raiseIndexError4(start_p2, ((s_p0 ? s_p0->Sup.len : 0)-1), (s_p0 ? s_p0->Sup.len : 0)); 	}
	result = npuParseFloat(((s_p0) ? ((NIM_CHAR*)s_p0->data+(start_p2)) : NIM_NIL), (((s_p0 ? s_p0->Sup.len : 0)-1))-(start_p2)+1, number_p1);
	return result;
}
