/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sstreams.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sstreams.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ;
typedef struct tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__vDrBeS6l6BRAY9c0GHoudsQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ttkEVvmYf0hsMP08MJMDuQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__Ae48H5ebeDGGPrl3XLNs4Q) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__CYTPrwuxH9aH4peeDNkliSw) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(NI, tyProc__ScPYATjQ5BT0khwFJ9cqRNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__N5reTQ4MoJsyv25NbYn5uQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__9axDJsqt9cvr06KdjeoLhOMg) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g {
  RootObj Sup;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ closeImpl;
	tyProc__ttkEVvmYf0hsMP08MJMDuQ atEndImpl;
	tyProc__Ae48H5ebeDGGPrl3XLNs4Q setPositionImpl;
	tyProc__CYTPrwuxH9aH4peeDNkliSw getPositionImpl;
	tyProc__ScPYATjQ5BT0khwFJ9cqRNQ readDataStrImpl;
	tyProc__N5reTQ4MoJsyv25NbYn5uQ readLineImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg readDataImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg peekDataImpl;
	tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ writeDataImpl;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ flushImpl;
};
struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ {
	NI a;
	NI b;
};
struct tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag {
  tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g Sup;
	NimStringDesc* data;
	NI pos;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
static N_NIMCALL(void, Marker_tyRef__XVU9b9c9ayvqppJbu9aGELFXhA)(void* p, NI op);
static N_INLINE(void, prepareMutation__system_u9255)(NimStringDesc** s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tyRef__LMHuTwqTaOH9bc5Gd3E8Zuw)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u746)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj_p0, TNimType* subclass_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u612)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u648)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, clamp__pureZstreams_u652)(NI x_p0, NI a_p1, NI b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u658)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u662)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u719)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u730)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u736)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s_p0, NI newLen_p1);
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_;
N_LIB_PRIVATE TNimType NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_;
N_LIB_PRIVATE TNimType NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_;
N_LIB_PRIVATE TNimType NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_;
N_LIB_PRIVATE TNimType NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_;
N_LIB_PRIVATE TNimType NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_;
N_LIB_PRIVATE TNimType NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_;
N_LIB_PRIVATE TNimType NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_;
N_LIB_PRIVATE TNimType NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_;
N_LIB_PRIVATE TNimType NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_;
N_LIB_PRIVATE TNimType NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_;
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
static N_NIMCALL(void, Marker_tyRef__XVU9b9c9ayvqppJbu9aGELFXhA)(void* p, NI op) {
	tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* a;
	a = (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g*)p;
}
static N_INLINE(void, prepareMutation__system_u9255)(NimStringDesc** s_p0) {
}
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	result = (NI)0;
	result = (*s_p0).readDataImpl(s_p0, buffer_p1, bufLen_p2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_u84)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2) {
	NI result;
	result = (NI)0;
	{
		if (!!(((*s_p0).readDataStrImpl == NIM_NIL))) goto LA3_;
		result = (*s_p0).readDataStrImpl(s_p0, buffer_p1, slice_p2);
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_3;
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_4;
		prepareMutation__system_u9255(buffer_p1);
		if (slice_p2.a < 0 || slice_p2.a >= ((*buffer_p1) ? (*buffer_p1)->Sup.len : 0)){ raiseIndexError2(slice_p2.a,((*buffer_p1) ? (*buffer_p1)->Sup.len : 0)-1); 		}
		if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_3)) { raiseOverflow(); 		};
		if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_3), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_4)) { raiseOverflow(); 		};
		result = readData__pureZstreams_u78(s_p0, ((void*) ((&(*buffer_p1)->data[slice_p2.a]))), (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_4));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s_p0 == 0));
		if (!(T3_)) goto LA4_;
		T3_ = !(((*s_p0).closeImpl == 0));
LA4_: ;
		if (!T3_) goto LA5_;
		(*s_p0).closeImpl(s_p0);
	}
LA5_: ;
}
static N_NIMCALL(void, Marker_tyRef__LMHuTwqTaOH9bc5Gd3E8Zuw)(void* p, NI op) {
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* a;
	a = (tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*)p;
	nimGCvisit((void*)(*a).data, op);
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u6026(p_p0);
	decRef__system_u6071(T1_);
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u746)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0) {
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	asgnRef((void**) (&(*s_2).data), ((NimStringDesc*) NIM_NIL));
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u612)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0) {
	NIM_BOOL result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
{	result = (NIM_BOOL)0;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	result = (((*s_2).data ? (*s_2).data->Sup.len : 0) <= (*s_2).pos);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u648)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NI pos_p1) {
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	(*s_2).pos = clamp__pureZstreams_u652(pos_p1, ((NI)0), ((*s_2).data ? (*s_2).data->Sup.len : 0));
}
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u658)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0) {
	NI result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
{	result = (NI)0;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	result = (*s_2).pos;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u662)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2) {
	NI result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_6;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_7;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_8;
	result = (NI)0;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	prepareMutation__system_u9255(buffer_p1);
	if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_6)) { raiseOverflow(); 	};
	if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_6), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_7)) { raiseOverflow(); 	};
	if (nimSubInt(((*s_2).data ? (*s_2).data->Sup.len : 0), (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_8)) { raiseOverflow(); 	};
	result = (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_7) <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_8)) ? (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_7) : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_8));
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_9;
		if (!(((NI)0) < result)) goto LA3_;
		{
			if (slice_p2.a < 0 || slice_p2.a >= ((*buffer_p1) ? (*buffer_p1)->Sup.len : 0)){ raiseIndexError2(slice_p2.a,((*buffer_p1) ? (*buffer_p1)->Sup.len : 0)-1); 			}
			if ((*s_2).pos < 0 || (*s_2).pos >= ((*s_2).data ? (*s_2).data->Sup.len : 0)){ raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->Sup.len : 0)-1); 			}
			if ((result) < ((NI)0) || (result) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(result, ((NI)0), ((NI)IL64(9223372036854775807))); 			}
			copyMem__system_u1759(((void*) ((&(*buffer_p1)->data[slice_p2.a]))), ((void*) ((&(*s_2).data->data[(*s_2).pos]))), ((NI) (result)));
		}
		if (nimAddInt((*s_2).pos, result, &TM__Ue7tnBcsL67VCiRfvt8q0A_9)) { raiseOverflow(); 		};
		(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_9);
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u719)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_10;
	result = (NI)0;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	if (nimSubInt(((*s_2).data ? (*s_2).data->Sup.len : 0), (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_10)) { raiseOverflow(); 	};
	result = ((bufLen_p2 <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_10)) ? bufLen_p2 : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_10));
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_11;
		if (!(((NI)0) < result)) goto LA3_;
		if ((*s_2).pos < 0 || (*s_2).pos >= ((*s_2).data ? (*s_2).data->Sup.len : 0)){ raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->Sup.len : 0)-1); 		}
		if ((result) < ((NI)0) || (result) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(result, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1759(buffer_p1, ((void*) ((&(*s_2).data->data[(*s_2).pos]))), ((NI) (result)));
		if (nimAddInt((*s_2).pos, result, &TM__Ue7tnBcsL67VCiRfvt8q0A_11)) { raiseOverflow(); 		};
		(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_11);
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u730)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_12;
	result = (NI)0;
	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	if (nimSubInt(((*s_2).data ? (*s_2).data->Sup.len : 0), (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_12)) { raiseOverflow(); 	};
	result = ((bufLen_p2 <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_12)) ? bufLen_p2 : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_12));
	{
		if (!(((NI)0) < result)) goto LA3_;
		if ((*s_2).pos < 0 || (*s_2).pos >= ((*s_2).data ? (*s_2).data->Sup.len : 0)){ raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->Sup.len : 0)-1); 		}
		if ((result) < ((NI)0) || (result) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(result, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1759(buffer_p1, ((void*) ((&(*s_2).data->data[(*s_2).pos]))), ((NI) (result)));
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u736)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2) {
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* s_2;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_15;
{	if (s_p0 && !isObj((*s_p0).Sup.m_type, (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_))){ raiseObjectConversionError(); 	}
	s_2 = ((tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) (s_p0));
	{
		if (!(bufLen_p2 <= ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_13;
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_14;
		if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_13)) { raiseOverflow(); 		};
		if (!(((*s_2).data ? (*s_2).data->Sup.len : 0) < (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_13))) goto LA7_;
		if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_14)) { raiseOverflow(); 		};
		if (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_14)) < ((NI)0) || ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_14)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_14), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		asgnRef((void**) (&(*s_2).data), setLengthStr((*s_2).data, ((NI) ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_14)))));
	}
LA7_: ;
	if ((*s_2).pos < 0 || (*s_2).pos >= ((*s_2).data ? (*s_2).data->Sup.len : 0)){ raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->Sup.len : 0)-1); 	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	copyMem__system_u1759(((void*) ((&(*s_2).data->data[(*s_2).pos]))), buffer_p1, ((NI) (bufLen_p2)));
	if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_15)) { raiseOverflow(); 	};
	(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_15);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*, newStringStream__pureZstreams_u749)(NimStringDesc* s_p0) {
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* result;
	NimStringDesc* T1_;
	result = NIM_NIL;
	result = (tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*) newObj((&NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_), sizeof(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag));
	(*result).Sup.Sup.m_type = (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_);
	T1_ = NIM_NIL;
	T1_ = (*result).data; (*result).data = copyStringRC1(s_p0);
	if (T1_) nimGCunrefNoCycle(T1_);
	prepareMutation__system_u9255((&(*result).data));
	(*result).pos = ((NI)0);
	(*result).Sup.closeImpl = ssClose__pureZstreams_u746;
	(*result).Sup.atEndImpl = ssAtEnd__pureZstreams_u612;
	(*result).Sup.setPositionImpl = ssSetPosition__pureZstreams_u648;
	(*result).Sup.getPositionImpl = ssGetPosition__pureZstreams_u658;
	(*result).Sup.readDataStrImpl = ssReadDataStr__pureZstreams_u662;
	(*result).Sup.readDataImpl = ssReadData__pureZstreams_u719;
	(*result).Sup.peekDataImpl = ssPeekData__pureZstreams_u730;
	(*result).Sup.writeDataImpl = ssWriteData__pureZstreams_u736;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsstreamsdotnim_DatInit000)(void) {
static TNimNode* TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[10];
static TNimNode* TM__Ue7tnBcsL67VCiRfvt8q0A_5_2[2];
static TNimNode TM__Ue7tnBcsL67VCiRfvt8q0A_0[14];
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.size = sizeof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g);
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.align = NIM_ALIGNOF(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g);
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.kind = 17;
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.flags = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[0] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[1];
NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_.size = sizeof(tyProc__vDrBeS6l6BRAY9c0GHoudsQ);
NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_.align = NIM_ALIGNOF(tyProc__vDrBeS6l6BRAY9c0GHoudsQ);
NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_.kind = 25;
NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_.base = 0;
NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, closeImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].typ = (&NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].name = "closeImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[1] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[2];
NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_.size = sizeof(tyProc__ttkEVvmYf0hsMP08MJMDuQ);
NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_.align = NIM_ALIGNOF(tyProc__ttkEVvmYf0hsMP08MJMDuQ);
NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_.kind = 25;
NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_.base = 0;
NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, atEndImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].typ = (&NTIprocLs58streamT58boolLOnimcall_gcsafeOT__ttkEVvmYf0hsMP08MJMDuQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].name = "atEndImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[2] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[3];
NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_.size = sizeof(tyProc__Ae48H5ebeDGGPrl3XLNs4Q);
NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_.align = NIM_ALIGNOF(tyProc__Ae48H5ebeDGGPrl3XLNs4Q);
NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_.kind = 25;
NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_.base = 0;
NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, setPositionImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].typ = (&NTIprocLs58stream_pos58intTLOnimcall_gcsafeOT__Ae48H5ebeDGGPrl3XLNs4Q_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].name = "setPositionImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[3] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[4];
NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_.size = sizeof(tyProc__CYTPrwuxH9aH4peeDNkliSw);
NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_.align = NIM_ALIGNOF(tyProc__CYTPrwuxH9aH4peeDNkliSw);
NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_.kind = 25;
NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_.base = 0;
NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, getPositionImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].typ = (&NTIprocLs58streamT58intLOnimcall_gcsafeOT__CYTPrwuxH9aH4peeDNkliSw_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].name = "getPositionImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[4] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[5];
NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_.size = sizeof(tyProc__ScPYATjQ5BT0khwFJ9cqRNQ);
NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_.align = NIM_ALIGNOF(tyProc__ScPYATjQ5BT0khwFJ9cqRNQ);
NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_.kind = 25;
NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_.base = 0;
NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, readDataStrImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].typ = (&NTIprocLs58stream_buffer58varstring_slice58sliceLsystemOintTT58intLOnimcall_gcsafeOT__ScPYATjQ5BT0khwFJ9cqRNQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].name = "readDataStrImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[5] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[6];
NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_.size = sizeof(tyProc__N5reTQ4MoJsyv25NbYn5uQ);
NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_.align = NIM_ALIGNOF(tyProc__N5reTQ4MoJsyv25NbYn5uQ);
NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_.kind = 25;
NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_.base = 0;
NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, readLineImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].typ = (&NTIprocLs58stream_line58varstringT58boolLOnimcall_gcsafeOT__N5reTQ4MoJsyv25NbYn5uQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].name = "readLineImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[6] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[7];
NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_.size = sizeof(tyProc__9axDJsqt9cvr06KdjeoLhOMg);
NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_.align = NIM_ALIGNOF(tyProc__9axDJsqt9cvr06KdjeoLhOMg);
NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_.kind = 25;
NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_.base = 0;
NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, readDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].typ = (&NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].name = "readDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[7] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[8];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, peekDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].typ = (&NTIprocLs58stream_buffer58pointer_buflen58intT58intLOnimcall_gcsafeOT__9axDJsqt9cvr06KdjeoLhOMg_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].name = "peekDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[8] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[9];
NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_.size = sizeof(tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ);
NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_.align = NIM_ALIGNOF(tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ);
NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_.kind = 25;
NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_.base = 0;
NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, writeDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].typ = (&NTIprocLs58stream_buffer58pointer_buflen58intTLOnimcall_gcsafeOT__EMT9b9b1dHUNH5MLNkNSOSNQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].name = "writeDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[9] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[10];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].offset = offsetof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g, flushImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].typ = (&NTIprocLs58streamTLOnimcall_gcsafeOT__vDrBeS6l6BRAY9c0GHoudsQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].name = "flushImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].len = 10; TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].kind = 2; TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].sons = &TM__Ue7tnBcsL67VCiRfvt8q0A_2_10[0];
NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_.node = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[0];
NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_.size = sizeof(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g*);
NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_.align = NIM_ALIGNOF(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g*);
NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_.kind = 22;
NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_.base = (&NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_);
NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_.marker = Marker_tyRef__XVU9b9c9ayvqppJbu9aGELFXhA;
NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_.size = sizeof(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag);
NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_.align = NIM_ALIGNOF(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag);
NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_.kind = 17;
NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_.base = (&NTIstreamobj__hNmHk9a6m386ZI9c8umyup7g_);
TM__Ue7tnBcsL67VCiRfvt8q0A_5_2[0] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[12];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[12].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[12].offset = offsetof(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag, data);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[12].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[12].name = "data";
TM__Ue7tnBcsL67VCiRfvt8q0A_5_2[1] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[13];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[13].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[13].offset = offsetof(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag, pos);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[13].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[13].name = "pos";
TM__Ue7tnBcsL67VCiRfvt8q0A_0[11].len = 2; TM__Ue7tnBcsL67VCiRfvt8q0A_0[11].kind = 2; TM__Ue7tnBcsL67VCiRfvt8q0A_0[11].sons = &TM__Ue7tnBcsL67VCiRfvt8q0A_5_2[0];
NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_.node = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[11];
NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_.size = sizeof(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*);
NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_.align = NIM_ALIGNOF(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*);
NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_.kind = 22;
NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_.base = (&NTIstringstreamobj__2VWq9a8gmGbkj9bGsucBK1ag_);
NTIstringstream__LMHuTwqTaOH9bc5Gd3E8Zuw_.marker = Marker_tyRef__LMHuTwqTaOH9bc5Gd3E8Zuw;
}

