/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@scollections@stables.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@scollections@stables.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ;
typedef struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w tySequence__9cCoiKBuW1Zm17EGUhnwT1w;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q tySequence__IfC4BMqPa86Eu3F1k8SL4Q;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ {
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* data;
	NI counter;
	NI first;
	NI last;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* Field3;
};
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
typedef NU8 tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw;
struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw kind;
union{
struct {	NimStringDesc* str;
} _kind_1;
struct {	NI64 num;
} _kind_2;
struct {	NF fnum;
} _kind_3;
struct {	NIM_BOOL bval;
} _kind_4;
struct {	tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ fields;
} _kind_6;
struct {	tySequence__IfC4BMqPa86Eu3F1k8SL4Q* elems;
} _kind_7;
};
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
struct tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ {
  tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g Sup;
};
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w {
  TGenericSeq Sup;
  tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg data[SEQ_DECL_SIZE];
};
struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* data[SEQ_DECL_SIZE];
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u222)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ_p0, NI len_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u438)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u283)(NimStringDesc* x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a_p0, NimStringDesc* b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1767)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u780)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u99)(NimStringDesc* msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u943)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1358)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, tySequence__9cCoiKBuW1Zm17EGUhnwT1w** data_p1, NimStringDesc* key_p2, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1640)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI hc_p2);
static N_INLINE(NI, rawGet__pureZjson_u2783)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3057)(NimStringDesc* key_p0);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
extern TNimType NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_;
STRING_LITERAL(TM__4SoG2KRQy3oMm9aUzSLtGrA_6, "hashcommon.nim(34, 9) `\012t.counter < t.dataLen` ", 47);
extern TNimType NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_;
extern TNimType NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_;
STRING_LITERAL(TM__4SoG2KRQy3oMm9aUzSLtGrA_15, "key not found: ", 15);
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
	result = (NI)0;
	if (nimMulInt(((NI) (count_p0)), ((NI)3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); 	};
	if (nimAddInt((NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2) / ((NI)2)), ((NI)4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); 	};
	result = nextPowerOfTwo__pureZmath_u222((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u132)(NI initialSize_p0, tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* Result) {
	NI correctSizeX60gensym0_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	(*Result).first = 0;
	(*Result).last = 0;
	if ((initialSize_p0) < ((NI)0) || (initialSize_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p0, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	correctSizeX60gensym0_ = slotsNeeded__pureZcollectionsZtables_u42(((NI) (initialSize_p0)));
	(*Result).counter = ((NI)0);
	if ((correctSizeX60gensym0_) < ((NI)0) || (correctSizeX60gensym0_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym0_, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__9cCoiKBuW1Zm17EGUhnwT1w*) newSeq((&NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_), ((NI) (correctSizeX60gensym0_))));
	(*Result).first = ((NI)-1);
	(*Result).last = ((NI)-1);
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = (int)0;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1767)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a_p0, NimStringDesc* b_p1) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a_p0 ? a_p0->Sup.len : 0);
	blen = (b_p1 ? b_p1->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1767(((void*) ((&a_p0->data[((NI)0)]))), ((void*) ((&b_p1->data[((NI)0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
	result = (NI)0;
	if (nimAddInt(h_p0, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); 	};
	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4) & maxHash_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u438)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI* hc_p2) {
	NI result;
	NI h;
	NI T10_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;
{	result = (NI)0;
	(*hc_p2) = hash__pureZhashes_u283(key_p1);
	{
		if (!((*hc_p2) == ((NI)0))) goto LA3_;
		(*hc_p2) = ((NI)314159265);
	}
LA3_: ;
	{
		NI T7_;
		T7_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
		if (!(T7_ == ((NI)0))) goto LA8_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA8_: ;
	T10_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
	h = (NI)((*hc_p2) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 			}
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T16_ = ((*t_p0).data->data[h].Field0 == (*hc_p2));
				if (!(T16_)) goto LA17_;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T16_ = eqStrings((*t_p0).data->data[h].Field2, key_p1);
LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
LA18_: ;
			T20_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_u34(h, T20_);
		} LA12: ;
	}
	if (nimSubInt(((NI)-1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) { raiseOverflow(); 	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u780)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
	result = (NIM_BOOL)0;
	{
		NI T3_;
		T3_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
		if (!!(((*t_p0).counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_6));
	}
LA4_: ;
	T6_ = (NIM_BOOL)0;
	T7_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
	if (nimMulInt(T7_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_7)) { raiseOverflow(); 	};
	if (nimMulInt((*t_p0).counter, ((NI)3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_8)) { raiseOverflow(); 	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_7) < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_8));
	if (T6_) goto LA8_;
	T9_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
	if (nimSubInt(T9_, (*t_p0).counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) { raiseOverflow(); 	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9) < ((NI)4));
LA8_: ;
	result = T6_;
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u6026(p_p0);
	decRef__system_u6071(T1_);
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1358)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, tySequence__9cCoiKBuW1Zm17EGUhnwT1w** data_p1, NimStringDesc* key_p2, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p3, NI hc_p4, NI h_p5) {
	NimStringDesc* T1_;
	if (h_p5 < 0 || h_p5 >= ((*data_p1) ? (*data_p1)->Sup.len : 0)){ raiseIndexError2(h_p5,((*data_p1) ? (*data_p1)->Sup.len : 0)-1); 	}
	T1_ = NIM_NIL;
	T1_ = (*data_p1)->data[h_p5].Field2; (*data_p1)->data[h_p5].Field2 = copyStringRC1(key_p2);
	if (T1_) nimGCunrefNoCycle(T1_);
	if (h_p5 < 0 || h_p5 >= ((*data_p1) ? (*data_p1)->Sup.len : 0)){ raiseIndexError2(h_p5,((*data_p1) ? (*data_p1)->Sup.len : 0)-1); 	}
	asgnRef((void**) (&(*data_p1)->data[h_p5].Field3), val_p3);
	if (h_p5 < 0 || h_p5 >= ((*data_p1) ? (*data_p1)->Sup.len : 0)){ raiseIndexError2(h_p5,((*data_p1) ? (*data_p1)->Sup.len : 0)-1); 	}
	(*data_p1)->data[h_p5].Field0 = hc_p4;
	if (h_p5 < 0 || h_p5 >= ((*data_p1) ? (*data_p1)->Sup.len : 0)){ raiseIndexError2(h_p5,((*data_p1) ? (*data_p1)->Sup.len : 0)-1); 	}
	(*data_p1)->data[h_p5].Field1 = ((NI)-1);
	{
		if (!((*t_p0).first < ((NI)0))) goto LA4_;
		(*t_p0).first = h_p5;
	}
LA4_: ;
	{
		if (!(((NI)0) <= (*t_p0).last)) goto LA8_;
		if ((*t_p0).last < 0 || (*t_p0).last >= ((*data_p1) ? (*data_p1)->Sup.len : 0)){ raiseIndexError2((*t_p0).last,((*data_p1) ? (*data_p1)->Sup.len : 0)-1); 		}
		(*data_p1)->data[(*t_p0).last].Field1 = h_p5;
	}
LA8_: ;
	(*t_p0).last = h_p5;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u943)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0) {
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* n;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_10;
	NI h;
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* T2_;
	n = NIM_NIL;
	T1_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
	if (nimMulInt(T1_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) { raiseOverflow(); 	};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) < ((NI)0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	n = (tySequence__9cCoiKBuW1Zm17EGUhnwT1w*) newSeq((&NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_), ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10))));
	h = (*t_p0).first;
	(*t_p0).first = ((NI)-1);
	(*t_p0).last = ((NI)-1);
	T2_ = NIM_NIL;
	T2_ = (*t_p0).data;
	unsureAsgnRef((void**) (&(*t_p0).data), n);
	n = T2_;
	{
		while (1) {
			NI nxt;
			NI eh;
			if (!(((NI)0) <= h)) goto LA4;
			if (h < 0 || h >= (n ? n->Sup.len : 0)){ raiseIndexError2(h,(n ? n->Sup.len : 0)-1); 			}
			nxt = n->data[h].Field1;
			if (h < 0 || h >= (n ? n->Sup.len : 0)){ raiseIndexError2(h,(n ? n->Sup.len : 0)-1); 			}
			eh = n->data[h].Field0;
			{
				NIM_BOOL T7_;
				NI j;
				NI T10_;
				NimStringDesc* T15_;
				tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_u31(eh);
				if (!T7_) goto LA8_;
				T10_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
				j = (NI)(eh & T10_);
				{
					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						if (j < 0 || j >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(j,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 						}
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data->data[j].Field0);
						if (!T13_) goto LA12;
						T14_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
						j = nextTry__pureZcollectionsZtables_u34(j, T14_);
					} LA12: ;
				}
				if (h < 0 || h >= (n ? n->Sup.len : 0)){ raiseIndexError2(h,(n ? n->Sup.len : 0)-1); 				}
				T15_ = NIM_NIL;
				T15_ = copyString(n->data[h].Field2);
				asgnRef((void**) (&n->data[h].Field2), NIM_NIL);
				if (h < 0 || h >= (n ? n->Sup.len : 0)){ raiseIndexError2(h,(n ? n->Sup.len : 0)-1); 				}
				T16_ = NIM_NIL;
				T16_ = n->data[h].Field3;
				asgnRef((void**) (&n->data[h].Field3), NIM_NIL);
				if (h < 0 || h >= (n ? n->Sup.len : 0)){ raiseIndexError2(h,(n ? n->Sup.len : 0)-1); 				}
				rawInsert__pureZjson_u1358(t_p0, (&(*t_p0).data), T15_, T16_, n->data[h].Field0, j);
			}
LA8_: ;
			h = nxt;
		} LA4: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1640)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI hc_p2) {
	NI result;
	NI h;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
		if (!(T3_ == ((NI)0))) goto LA4_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
	h = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T12_ = ((*t_p0).data->data[h].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T12_ = eqStrings((*t_p0).data->data[h].Field2, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
LA14_: ;
			T16_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_u34(h, T16_);
		} LA8: ;
	}
	if (nimSubInt(((NI)-1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) { raiseOverflow(); 	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u369)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p2) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym13_;
		T3_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym13_ = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
		(*t_p0).counter = ((NI)0);
		if ((correctSizeX60gensym13_) < ((NI)0) || (correctSizeX60gensym13_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym13_, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		unsureAsgnRef((void**) (&(*t_p0).data), (tySequence__9cCoiKBuW1Zm17EGUhnwT1w*) newSeq((&NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_), ((NI) (correctSizeX60gensym13_))));
		(*t_p0).first = ((NI)-1);
		(*t_p0).last = ((NI)-1);
	}
LA4_: ;
	hc = (NI)0;
	index = rawGet__pureZjson_u438((&(*t_p0)), key_p1, (&hc));
	{
		if (!(((NI)0) <= index)) goto LA8_;
		if (index < 0 || index >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(index,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 		}
		asgnRef((void**) (&(*t_p0).data->data[index].Field3), val_p2);
	}
	goto LA6_;
LA8_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
		{
			NI T13_;
			NI correctSizeX60gensym18_;
			T13_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
			if (!(T13_ == ((NI)0))) goto LA14_;
			correctSizeX60gensym18_ = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
			(*t_p0).counter = ((NI)0);
			if ((correctSizeX60gensym18_) < ((NI)0) || (correctSizeX60gensym18_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym18_, ((NI)0), ((NI)IL64(9223372036854775807))); 			}
			unsureAsgnRef((void**) (&(*t_p0).data), (tySequence__9cCoiKBuW1Zm17EGUhnwT1w*) newSeq((&NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_), ((NI) (correctSizeX60gensym18_))));
			(*t_p0).first = ((NI)-1);
			(*t_p0).last = ((NI)-1);
		}
LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__pureZjson_u780((&(*t_p0)));
			if (!T18_) goto LA19_;
			enlarge__pureZjson_u943(t_p0);
			index = rawGetKnownHC__pureZjson_u1640((&(*t_p0)), key_p1, hc);
		}
LA19_: ;
		if (nimSubInt(((NI)-1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); 		};
		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12);
		rawInsert__pureZjson_u1358(t_p0, (&(*t_p0).data), key_p1, val_p2, hc, index);
		if (nimAddInt((*t_p0).counter, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); 		};
		(*t_p0).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13);
	}
LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u2702)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__pureZjson_u438(t_p0, key_p1, (&hc));
	result = (((NI)0) <= T1_);
	return result;
}
static N_INLINE(NI, rawGet__pureZjson_u2783)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, NI* hc_p2) {
	NI result;
	NI h;
	NI T10_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
{	result = (NI)0;
	(*hc_p2) = hash__pureZhashes_u283(key_p1);
	{
		if (!((*hc_p2) == ((NI)0))) goto LA3_;
		(*hc_p2) = ((NI)314159265);
	}
LA3_: ;
	{
		NI T7_;
		T7_ = ((*t_p0).data ? (*t_p0).data->Sup.len : 0);
		if (!(T7_ == ((NI)0))) goto LA8_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA8_: ;
	T10_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
	h = (NI)((*hc_p2) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 			}
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T16_ = ((*t_p0).data->data[h].Field0 == (*hc_p2));
				if (!(T16_)) goto LA17_;
				if (h < 0 || h >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(h,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 				}
				T16_ = eqStrings((*t_p0).data->data[h].Field2, key_p1);
LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
LA18_: ;
			T20_ = (((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_u34(h, T20_);
		} LA12: ;
	}
	if (nimSubInt(((NI)-1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); 	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1) {
	{
		if (!!((src_p1 == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_u1759(((void*) ((&(*dest_p0).data[(*dest_p0).Sup.len]))), ((void*) ((*src_p1).data)), ((NI) ((NI)((*src_p1).Sup.len + ((NI)1)))));
		(*dest_p0).Sup.len += (*src_p1).Sup.len;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3057)(NimStringDesc* key_p0) {
	tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ*) newObj((&NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_), sizeof(tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_ = NIM_NIL;
	T2_ = rawNewString((key_p0 ? key_p0->Sup.len : 0) + 15);
appendString(T2_, ((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_15));
appendString(T2_, key_p0);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 235);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA**, X5BX5D___pureZjson_u2776)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA** result;
	NI hcX60gensym89_;
	NI indexX60gensym89_;
	result = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA**)0;
	hcX60gensym89_ = (NI)0;
	indexX60gensym89_ = rawGet__pureZjson_u2783((&(*t_p0)), key_p1, (&hcX60gensym89_));
	{
		if (!(((NI)0) <= indexX60gensym89_)) goto LA3_;
		if (indexX60gensym89_ < 0 || indexX60gensym89_ >= ((*t_p0).data ? (*t_p0).data->Sup.len : 0)){ raiseIndexError2(indexX60gensym89_,((*t_p0).data ? (*t_p0).data->Sup.len : 0)-1); 		}
		result = &(*t_p0).data->data[indexX60gensym89_].Field3;
	}
	goto LA1_;
LA3_: ;
	{
		raiseKeyError__pureZjson_u3057(key_p1);
	}
LA1_: ;
	return result;
}
