/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@ssystem@sexceptions.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@ssystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
struct tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ {
  tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g Sup;
};
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tyRef__HgEFWyabOzsO4jKa9bLle2w)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__9aFqVR9bC56KFH7LAVx1G9cOQ)(void* p, NI op);
extern TNimType NTIcatchableerror__plmui9cLQDf1IsFzhQAAHyg_;
N_LIB_PRIVATE TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
N_LIB_PRIVATE TNimType NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_;
N_LIB_PRIVATE TNimType NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_;
N_LIB_PRIVATE TNimType NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_;
static N_NIMCALL(void, Marker_tyRef__HgEFWyabOzsO4jKa9bLle2w)(void* p, NI op) {
	tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g* a;
	a = (tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}
static N_NIMCALL(void, Marker_tyRef__9aFqVR9bC56KFH7LAVx1G9cOQ)(void* p, NI op) {
	tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ* a;
	a = (tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsexceptionsdotnim_DatInit000)(void) {
static TNimNode TM__TzI3paKQY09cLjc9cmCvur3A_0[2];
NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_.size = sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g);
NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_.align = NIM_ALIGNOF(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g);
NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_.kind = 17;
NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_.base = (&NTIcatchableerror__plmui9cLQDf1IsFzhQAAHyg_);
TM__TzI3paKQY09cLjc9cmCvur3A_0[0].len = 0; TM__TzI3paKQY09cLjc9cmCvur3A_0[0].kind = 2;
NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_.node = &TM__TzI3paKQY09cLjc9cmCvur3A_0[0];
NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_.size = sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*);
NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_.align = NIM_ALIGNOF(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*);
NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_.kind = 22;
NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_.base = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_.marker = Marker_tyRef__HgEFWyabOzsO4jKa9bLle2w;
NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_.size = sizeof(tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ);
NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_.align = NIM_ALIGNOF(tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ);
NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_.kind = 17;
NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_.base = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
TM__TzI3paKQY09cLjc9cmCvur3A_0[1].len = 0; TM__TzI3paKQY09cLjc9cmCvur3A_0[1].kind = 2;
NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_.node = &TM__TzI3paKQY09cLjc9cmCvur3A_0[1];
NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_.size = sizeof(tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ*);
NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_.align = NIM_ALIGNOF(tyObject_KeyError__xpJ5te9aPzShdqxBJRfq4wQ*);
NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_.kind = 22;
NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_.base = (&NTIkeyerror__xpJ5te9aPzShdqxBJRfq4wQ_);
NTIrefkeyerror__9aFqVR9bC56KFH7LAVx1G9cOQ_.marker = Marker_tyRef__9aFqVR9bC56KFH7LAVx1G9cOQ;
}

