/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@slexbase.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@slexbase.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g;
typedef struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg {
  RootObj Sup;
	NI bufpos;
	NimStringDesc* buf;
	tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef N_NIMCALL_PTR(void, tyProc__vDrBeS6l6BRAY9c0GHoudsQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ttkEVvmYf0hsMP08MJMDuQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__Ae48H5ebeDGGPrl3XLNs4Q) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__CYTPrwuxH9aH4peeDNkliSw) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__ScPYATjQ5BT0khwFJ9cqRNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__N5reTQ4MoJsyv25NbYn5uQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__9axDJsqt9cvr06KdjeoLhOMg) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g {
  RootObj Sup;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ closeImpl;
	tyProc__ttkEVvmYf0hsMP08MJMDuQ atEndImpl;
	tyProc__Ae48H5ebeDGGPrl3XLNs4Q setPositionImpl;
	tyProc__CYTPrwuxH9aH4peeDNkliSw getPositionImpl;
	tyProc__ScPYATjQ5BT0khwFJ9cqRNQ readDataStrImpl;
	tyProc__N5reTQ4MoJsyv25NbYn5uQ readLineImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg readDataImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg peekDataImpl;
	tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ writeDataImpl;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ flushImpl;
};
struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u99)(NimStringDesc* msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_NIMCALL(NimStringDesc*, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, fillBuffer__pureZlexbase_u16)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0);
static N_INLINE(void, moveMem__system_u1763)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_u84)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2);
static N_INLINE(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom__pureZlexbase_u132)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0);
N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer__pureZlexbase_u78)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_;
extern TNimType NTIchar__nmiMWKVIe46vacnhAFrQvw_;
N_LIB_PRIVATE TNimType NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_;
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_3, "lexbase.nim(140, 9) `bufLen > 0` ", 33);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_4, "lexbase.nim(141, 9) `input != nil` ", 35);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_7, "lexbase.nim(54, 9) `L.sentinel + 1 <= L.buf.len` ", 49);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_10, "lexbase.nim(56, 9) `toCopy >= 0` ", 33);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_18, "lexbase.nim(78, 13) `s < L.buf.len` ", 36);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_27, "lexbase.nim(110, 9) `L.buf[pos] == \'\\r\'` ", 41);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_29, "lexbase.nim(97, 9) `pos <= L.sentinel` ", 39);
STRING_LITERAL(TM__k6p5NxDJat9aTyZxfZjCDJQ_32, "lexbase.nim(121, 9) `L.buf[pos] == \'\\n\'` ", 41);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, moveMem__system_u1763)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memmove(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ));
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fillBuffer__pureZlexbase_u16)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0) {
	NI charsRead;
	NI toCopy;
	NI s;
	NI oldBufLen;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_8;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_9;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_12;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_13;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_14;
	tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ T13_;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_15;
	charsRead = (NI)0;
	toCopy = (NI)0;
	s = (NI)0;
	oldBufLen = (NI)0;
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_6;
		if (nimAddInt((*L_p0).sentinel, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_6)) { raiseOverflow(); 		};
		if (!!(((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_6) <= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_7));
	}
LA3_: ;
	if (nimAddInt((*L_p0).sentinel, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_8)) { raiseOverflow(); 	};
	if (nimSubInt(((*L_p0).buf ? (*L_p0).buf->Sup.len : 0), (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_8), &TM__k6p5NxDJat9aTyZxfZjCDJQ_9)) { raiseOverflow(); 	};
	toCopy = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_9);
	{
		if (!!((((NI)0) <= toCopy))) goto LA7_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_10));
	}
LA7_: ;
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_11;
		if (!(((NI)0) < toCopy)) goto LA11_;
		if (((NI)0) < 0 || ((NI)0) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(((NI)0),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		if (nimAddInt((*L_p0).sentinel, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_11)) { raiseOverflow(); 		};
		if ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_11) < 0 || (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_11) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_11),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		if ((toCopy) < ((NI)0) || (toCopy) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toCopy, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		moveMem__system_u1763(((void*) ((&(*L_p0).buf->data[((NI)0)]))), ((void*) ((&(*L_p0).buf->data[(NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_11)]))), ((NI) (toCopy)));
	}
LA11_: ;
	if (nimAddInt(toCopy, (*L_p0).sentinel, &TM__k6p5NxDJat9aTyZxfZjCDJQ_12)) { raiseOverflow(); 	};
	if (nimAddInt((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_12), ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_13)) { raiseOverflow(); 	};
	if (nimSubInt((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_13), ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_14)) { raiseOverflow(); 	};
	T13_ = dotdot___stdZstrbasics_u48(toCopy, (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_14));
	charsRead = readDataStr__pureZstreams_u84((*L_p0).input, (&(*L_p0).buf), T13_);
	if (nimAddInt(toCopy, charsRead, &TM__k6p5NxDJat9aTyZxfZjCDJQ_15)) { raiseOverflow(); 	};
	s = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_15);
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_16;
		if (nimAddInt((*L_p0).sentinel, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_16)) { raiseOverflow(); 		};
		if (!(charsRead < (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_16))) goto LA16_;
		if (s < 0 || s >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(s,((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		(*L_p0).buf->data[s] = 0;
		(*L_p0).sentinel = s;
	}
	goto LA14_;
LA16_: ;
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_17;
		if (nimSubInt(s, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_17)) { raiseOverflow(); 		};
		s = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_17);
		{
			while (1) {
				{
					if (!!((s < ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)))) goto LA23_;
					failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_18));
				}
LA23_: ;
				{
					while (1) {
						NIM_BOOL T27_;
						NI TM__k6p5NxDJat9aTyZxfZjCDJQ_19;
						T27_ = (NIM_BOOL)0;
						T27_ = (((NI)0) <= s);
						if (!(T27_)) goto LA28_;
						if (s < 0 || s >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(s,((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 						}
						T27_ = !((((*L_p0).refillChars[(NU)((((NU8)((*L_p0).buf->data[s]))))>>3] &(1U<<((NU)((((NU8)((*L_p0).buf->data[s]))))&7U)))!=0));
LA28_: ;
						if (!T27_) goto LA26;
						if (nimSubInt(s, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_19)) { raiseOverflow(); 						};
						s = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_19);
					} LA26: ;
				}
				{
					if (!(((NI)0) <= s)) goto LA31_;
					(*L_p0).sentinel = s;
					goto LA19;
				}
				goto LA29_;
LA31_: ;
				{
					NI TM__k6p5NxDJat9aTyZxfZjCDJQ_20;
					NI TM__k6p5NxDJat9aTyZxfZjCDJQ_21;
					tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ T34_;
					NI TM__k6p5NxDJat9aTyZxfZjCDJQ_24;
					oldBufLen = ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0);
					if (nimMulInt(((*L_p0).buf ? (*L_p0).buf->Sup.len : 0), ((NI)2), &TM__k6p5NxDJat9aTyZxfZjCDJQ_20)) { raiseOverflow(); 					};
					if (((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_20)) < ((NI)0) || ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_20)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_20), ((NI)0), ((NI)IL64(9223372036854775807))); 					}
					unsureAsgnRef((void**) (&(*L_p0).buf), setLengthStr((*L_p0).buf, ((NI) ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_20)))));
					if (nimSubInt(((*L_p0).buf ? (*L_p0).buf->Sup.len : 0), ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_21)) { raiseOverflow(); 					};
					T34_ = dotdot___stdZstrbasics_u48(oldBufLen, (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_21));
					charsRead = readDataStr__pureZstreams_u84((*L_p0).input, (&(*L_p0).buf), T34_);
					{
						NI TM__k6p5NxDJat9aTyZxfZjCDJQ_22;
						NI TM__k6p5NxDJat9aTyZxfZjCDJQ_23;
						if (!(charsRead < oldBufLen)) goto LA37_;
						if (nimAddInt(oldBufLen, charsRead, &TM__k6p5NxDJat9aTyZxfZjCDJQ_22)) { raiseOverflow(); 						};
						if ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_22) < 0 || (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_22) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_22),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 						}
						(*L_p0).buf->data[(NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_22)] = 0;
						if (nimAddInt(oldBufLen, charsRead, &TM__k6p5NxDJat9aTyZxfZjCDJQ_23)) { raiseOverflow(); 						};
						(*L_p0).sentinel = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_23);
						goto LA19;
					}
LA37_: ;
					if (nimSubInt(((*L_p0).buf ? (*L_p0).buf->Sup.len : 0), ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_24)) { raiseOverflow(); 					};
					s = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_24);
				}
LA29_: ;
			}
		} LA19: ;
	}
LA14_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom__pureZlexbase_u132)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0) {
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_25;
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_26;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		if (((NI)0) < 0 || ((NI)0) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(((NI)0),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		T4_ = ((NU8)((*L_p0).buf->data[((NI)0)]) == (NU8)(239));
		if (!(T4_)) goto LA5_;
		if (((NI)1) < 0 || ((NI)1) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(((NI)1),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		T4_ = ((NU8)((*L_p0).buf->data[((NI)1)]) == (NU8)(187));
LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		if (((NI)2) < 0 || ((NI)2) >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(((NI)2),((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		T3_ = ((NU8)((*L_p0).buf->data[((NI)2)]) == (NU8)(191));
LA6_: ;
		if (!T3_) goto LA7_;
		if (nimAddInt((*L_p0).bufpos, ((NI)3), &TM__k6p5NxDJat9aTyZxfZjCDJQ_25)) { raiseOverflow(); 		};
		(*L_p0).bufpos = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_25);
		if (nimAddInt((*L_p0).lineStart, ((NI)3), &TM__k6p5NxDJat9aTyZxfZjCDJQ_26)) { raiseOverflow(); 		};
		(*L_p0).lineStart = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_26);
	}
LA7_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_u144)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input_p1, NI bufLen_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars_p3) {
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_5;
	{
		if (!!((((NI)0) < bufLen_p2))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_3));
	}
LA3_: ;
	{
		if (!!(!((input_p1 == ((tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g*) NIM_NIL))))) goto LA7_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_4));
	}
LA7_: ;
	unsureAsgnRef((void**) (&(*L_p0).input), input_p1);
	(*L_p0).bufpos = ((NI)0);
	(*L_p0).offsetBase = ((NI)0);
	nimCopyMem((void*)(*L_p0).refillChars, (NIM_CONST void*)refillChars_p3, 32);
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	unsureAsgnRef((void**) (&(*L_p0).buf), mnewString(((NI) (bufLen_p2))));
	if (nimSubInt(bufLen_p2, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_5)) { raiseOverflow(); 	};
	(*L_p0).sentinel = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_5);
	(*L_p0).lineStart = ((NI)0);
	(*L_p0).lineNumber = ((NI)1);
	fillBuffer__pureZlexbase_u16(L_p0);
	skipUtf8Bom__pureZlexbase_u132(L_p0);
}
N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer__pureZlexbase_u78)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1) {
	NI result;
	result = (NI)0;
	{
		if (!!((pos_p1 <= (*L_p0).sentinel))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_29));
	}
LA3_: ;
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_30;
		if (!(pos_p1 < (*L_p0).sentinel)) goto LA7_;
		if (nimAddInt(pos_p1, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_30)) { raiseOverflow(); 		};
		result = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_30);
	}
	goto LA5_;
LA7_: ;
	{
		NI TM__k6p5NxDJat9aTyZxfZjCDJQ_31;
		fillBuffer__pureZlexbase_u16(L_p0);
		if (nimAddInt((*L_p0).offsetBase, pos_p1, &TM__k6p5NxDJat9aTyZxfZjCDJQ_31)) { raiseOverflow(); 		};
		(*L_p0).offsetBase = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_31);
		(*L_p0).bufpos = ((NI)0);
		result = ((NI)0);
	}
LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_u91)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1) {
	NI result;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_28;
	result = (NI)0;
	{
		if (pos_p1 < 0 || pos_p1 >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(pos_p1,((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		if (!!(((NU8)((*L_p0).buf->data[pos_p1]) == (NU8)(13)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_27));
	}
LA3_: ;
	if (nimAddInt((*L_p0).lineNumber, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_28)) { raiseOverflow(); 	};
	(*L_p0).lineNumber = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_28);
	result = fillBaseLexer__pureZlexbase_u78(L_p0, pos_p1);
	{
		if (result < 0 || result >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(result,((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		if (!((NU8)((*L_p0).buf->data[result]) == (NU8)(10))) goto LA7_;
		result = fillBaseLexer__pureZlexbase_u78(L_p0, result);
	}
LA7_: ;
	(*L_p0).lineStart = result;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_u105)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1) {
	NI result;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_33;
	result = (NI)0;
	{
		if (pos_p1 < 0 || pos_p1 >= ((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)){ raiseIndexError2(pos_p1,((*L_p0).buf ? (*L_p0).buf->Sup.len : 0)-1); 		}
		if (!!(((NU8)((*L_p0).buf->data[pos_p1]) == (NU8)(10)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__k6p5NxDJat9aTyZxfZjCDJQ_32));
	}
LA3_: ;
	if (nimAddInt((*L_p0).lineNumber, ((NI)1), &TM__k6p5NxDJat9aTyZxfZjCDJQ_33)) { raiseOverflow(); 	};
	(*L_p0).lineNumber = (NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_33);
	result = fillBaseLexer__pureZlexbase_u78(L_p0, pos_p1);
	(*L_p0).lineStart = result;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_u163)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0, NI pos_p1) {
	NI result;
	NI TM__k6p5NxDJat9aTyZxfZjCDJQ_34;
	result = (NI)0;
	if (nimSubInt(pos_p1, (*L_p0).lineStart, &TM__k6p5NxDJat9aTyZxfZjCDJQ_34)) { raiseOverflow(); 	};
	if ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_34) == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); 	}
	result = ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_34) > 0? ((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_34)) : -((NI)(TM__k6p5NxDJat9aTyZxfZjCDJQ_34)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_u14)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0) {
	close__pureZstreams_u57((*L_p0).input);
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatslexbasedotnim_DatInit000)(void) {
static TNimNode* TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[8];
static TNimNode TM__k6p5NxDJat9aTyZxfZjCDJQ_0[10];
NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_.size = sizeof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg);
NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_.align = NIM_ALIGNOF(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg);
NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_.kind = 17;
NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[0] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[1];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[1].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[1].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, bufpos);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[1].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[1].name = "bufpos";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[1] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[2];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[2].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[2].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, buf);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[2].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[2].name = "buf";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[2] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[3];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[3].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[3].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, input);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[3].typ = (&NTIstream__XVU9b9c9ayvqppJbu9aGELFXhA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[3].name = "input";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[3] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[4];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[4].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[4].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, lineNumber);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[4].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[4].name = "lineNumber";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[4] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[5];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[5].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[5].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, sentinel);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[5].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[5].name = "sentinel";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[5] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[6];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[6].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[6].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, lineStart);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[6].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[6].name = "lineStart";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[6] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[7];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[7].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[7].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, offsetBase);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[7].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[7].name = "offsetBase";
TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[7] = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[8];
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.size = sizeof(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.align = NIM_ALIGNOF(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.kind = 19;
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.base = (&NTIchar__nmiMWKVIe46vacnhAFrQvw_);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.flags = 3;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[9].len = 0; TM__k6p5NxDJat9aTyZxfZjCDJQ_0[9].kind = 0;
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.node = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[9];
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[8].kind = 1;
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[8].offset = offsetof(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg, refillChars);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[8].typ = (&NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_);
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[8].name = "refillChars";
TM__k6p5NxDJat9aTyZxfZjCDJQ_0[0].len = 8; TM__k6p5NxDJat9aTyZxfZjCDJQ_0[0].kind = 2; TM__k6p5NxDJat9aTyZxfZjCDJQ_0[0].sons = &TM__k6p5NxDJat9aTyZxfZjCDJQ_2_8[0];
NTIbaselexer__6nHBcS9cBoISVEBovO9cEAHg_.node = &TM__k6p5NxDJat9aTyZxfZjCDJQ_0[0];
}

