/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sstrutils.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, parseBiggestInt__pureZparseutils_u894)(NimStringDesc* s_p0, NI64* number_p1, NI start_p2);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space_p0);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u924)(NimStringDesc* s_p0, NF* number_p1, NI start_p2);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringDesc** s_p0, NimStringDesc* formatstr_p1, NimStringDesc** a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2497)(NimStringDesc* formatstr_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest_p0, NI addlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2484)(NimStringDesc* x_p0, NimStringDesc** inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a_p0, NimStringDesc* b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__system_u9104)(NimStringDesc* s_p0, NI first_p1, NI last_p2);
extern TNimType NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_;
extern TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3, "invalid integer: ", 17);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4, "invalid float: ", 15);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8, "invalid format string: ", 23);
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3) {
	NI result;
	NI last_2;
{	result = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		last_2 = ((s_p0 ? s_p0->Sup.len : 0)-1);
	}
	goto LA1_;
LA3_: ;
	{
		last_2 = last_p3;
	}
LA1_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (start_p2));
		res = colontmp_;
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
				if (!(res <= last_2)) goto LA8;
				i = res;
				{
					if (i < 0 || i >= (s_p0 ? s_p0->Sup.len : 0)){ raiseIndexError2(i,(s_p0 ? s_p0->Sup.len : 0)-1); 					}
					if (!((chars_p1[(NU)((((NU8)(s_p0->data[i]))))>>3] &(1U<<((NU)((((NU8)(s_p0->data[i]))))&7U)))!=0)) goto LA11_;
					result = i;
					goto BeforeRet_;
				}
LA11_: ;
				if (nimAddInt(res, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); 				};
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1873)(NimStringDesc* s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindCharSet(s_p0, chars_p1, ((NI)0), ((NI)-1));
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1) {
	{
		if (!!((src_p1 == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_u1759(((void*) ((&(*dest_p0).data[(*dest_p0).Sup.len]))), ((void*) ((*src_p1).data)), ((NI) ((NI)((*src_p1).Sup.len + ((NI)1)))));
		(*dest_p0).Sup.len += (*src_p1).Sup.len;
	}
LA3_: ;
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s_p0) {
	NI64 result;
	NI L;
	result = (NI64)0;
	result = IL64(0);
	L = parseBiggestInt__pureZparseutils_u894(s_p0, (&result), ((NI)0));
	{
		NIM_BOOL T3_;
		tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L == (s_p0 ? s_p0->Sup.len : 0)));
		if (T3_) goto LA4_;
		T3_ = (L == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*) newObj((&NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_), sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_ = NIM_NIL;
		T8_ = rawNewString((s_p0 ? s_p0->Sup.len : 0) + 17);
appendString(T8_, ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3));
appendString(T8_, s_p0);
		asgnRef((void**) (&(*T7_).Sup.Sup.message), T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseBiggestInt", "strutils.nim", 1147);
	}
LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s_p0) {
	NF result;
	NI L;
	result = (NF)0;
	result = 0.0;
	L = parseFloat__pureZparseutils_u924(s_p0, (&result), ((NI)0));
	{
		NIM_BOOL T3_;
		tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L == (s_p0 ? s_p0->Sup.len : 0)));
		if (T3_) goto LA4_;
		T3_ = (L == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*) newObj((&NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_), sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_ = NIM_NIL;
		T8_ = rawNewString((s_p0 ? s_p0->Sup.len : 0) + 15);
appendString(T8_, ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4));
appendString(T8_, s_p0);
		asgnRef((void**) (&(*T7_).Sup.Sup.message), T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "strutils.nim", 1179);
	}
LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2497)(NimStringDesc* formatstr_p0) {
	tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g*) newObj((&NTIrefvalueerror__HgEFWyabOzsO4jKa9bLle2w_), sizeof(tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_ = NIM_NIL;
	T2_ = rawNewString((formatstr_p0 ? formatstr_p0->Sup.len : 0) + 23);
appendString(T2_, ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8));
appendString(T2_, formatstr_p0);
	asgnRef((void**) (&(*T1_).Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "strutils.nim", 2757);
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	result = (NIM_CHAR)0;
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		if (nimAddInt(((NU8)(c_p0)), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); 		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28), ((NI)0), ((NI)255)); 		}
		result = ((NIM_CHAR) (((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a_p0, NimStringDesc* b_p1) {
	NI result;
	NI aLenX60gensym24_;
	NI bLenX60gensym24_;
	NI iX60gensym24_;
	NI jX60gensym24_;
{	result = (NI)0;
	aLenX60gensym24_ = (a_p0 ? a_p0->Sup.len : 0);
	bLenX60gensym24_ = (b_p1 ? b_p1->Sup.len : 0);
	iX60gensym24_ = ((NI)0);
	jX60gensym24_ = ((NI)0);
	{
		while (1) {
			NIM_CHAR aaX60gensym24_;
			NIM_CHAR bbX60gensym24_;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24_ < aLenX60gensym24_);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0->data[iX60gensym24_]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24_ += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24_ < bLenX60gensym24_);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1->data[jX60gensym24_]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24_ += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24_ < aLenX60gensym24_)) goto LA13_;
				aaX60gensym24_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0->data[iX60gensym24_]);
			}
			goto LA11_;
LA13_: ;
			{
				aaX60gensym24_ = 0;
			}
LA11_: ;
			{
				if (!(jX60gensym24_ < bLenX60gensym24_)) goto LA18_;
				bbX60gensym24_ = toLowerAscii__stdZprivateZstrimpl_u1(b_p1->data[jX60gensym24_]);
			}
			goto LA16_;
LA18_: ;
			{
				bbX60gensym24_ = 0;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24_)) - ((NU8)(bbX60gensym24_)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24_ <= iX60gensym24_)) goto LA27_;
				{
					if (!(bLenX60gensym24_ <= jX60gensym24_)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24_ <= jX60gensym24_)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24_ += ((NI)1);
			jX60gensym24_ += ((NI)1);
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2484)(NimStringDesc* x_p0, NimStringDesc** inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i;
{	result = (NI)0;
	i = ((NI)0);
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
			if (!(i < (inArray_p1Len_0-1))) goto LA2;
			{
				NI T5_;
				if (i < 0 || i >= inArray_p1Len_0){ raiseIndexError2(i,inArray_p1Len_0-1); 				}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i]);
				if (!(T5_ == ((NI)0))) goto LA6_;
				result = i;
				goto BeforeRet_;
			}
LA6_: ;
			if (nimAddInt(i, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); 			};
			i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
		} LA2: ;
	}
	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringDesc** s_p0, NimStringDesc* formatstr_p1, NimStringDesc** a_p2, NI a_p2Len_0) {
	NI i;
	NI num;
	i = ((NI)0);
	num = ((NI)0);
	{
		while (1) {
			if (!(i < (formatstr_p1 ? formatstr_p1->Sup.len : 0))) goto LA2;
			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
				T5_ = (NIM_BOOL)0;
				if (i < 0 || i >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(i,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 				}
				T5_ = ((NU8)(formatstr_p1->data[i]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); 				};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6) < (formatstr_p1 ? formatstr_p1->Sup.len : 0));
LA6_: ;
				if (!T5_) goto LA7_;
				if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); 				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7) >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7),(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 				}
				switch (((NU8)(formatstr_p1->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
					{
						if (!((a_p2Len_0-1) < num)) goto LA12_;
						invalidFormatString__pureZstrutils_u2497(formatstr_p1);
					}
LA12_: ;
					if (num < 0 || num >= a_p2Len_0){ raiseIndexError2(num,a_p2Len_0-1); 					}
					unsureAsgnRef((void**) (&(*s_p0)), resizeString((*s_p0), (a_p2[num] ? a_p2[num]->Sup.len : 0) + 0));
appendString((*s_p0), a_p2[num]);
					if (nimAddInt(i, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); 					};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
					if (nimAddInt(num, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); 					};
					num = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
					unsureAsgnRef((void**) (&(*s_p0)), addChar((*s_p0), 36));
					if (nimAddInt(i, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); 					};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
					NIM_BOOL negative;
					NI idx;
					j = ((NI)0);
					if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); 					};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
					if (i < 0 || i >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(i,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 					}
					negative = ((NU8)(formatstr_p1->data[i]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
						if (!negative) goto LA18_;
						if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); 						};
						i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
					}
LA18_: ;
					{
						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
							T22_ = (NIM_BOOL)0;
							T22_ = (i < (formatstr_p1 ? formatstr_p1->Sup.len : 0));
							if (!(T22_)) goto LA23_;
							if (i < 0 || i >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(i,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 							}
							T22_ = (((NU8)(formatstr_p1->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr_p1->data[i])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							if (nimMulInt(j, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); 							};
							if (i < 0 || i >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(i,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 							}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14), ((NU8)(formatstr_p1->data[i])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); 							};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); 							};
							j = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
							if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); 							};
							i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
						} LA21: ;
					}
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
						if (!!(negative)) goto LA26_;
						if (nimSubInt(j, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); 						};
						idx = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
					}
					goto LA24_;
LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
						if (nimSubInt(a_p2Len_0, j, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); 						};
						idx = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
					}
LA24_: ;
					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_u2497(formatstr_p1);
					}
LA33_: ;
					if (idx < 0 || idx >= a_p2Len_0){ raiseIndexError2(idx,a_p2Len_0-1); 					}
					unsureAsgnRef((void**) (&(*s_p0)), resizeString((*s_p0), (a_p2[idx] ? a_p2[idx]->Sup.len : 0) + 0));
appendString((*s_p0), a_p2[idx]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
					NI k;
					NIM_BOOL negative_2;
					NI isNumber;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
					if (nimAddInt(i, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); 					};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20);
					k = ((NI)0);
					if (j_2 < 0 || j_2 >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 					}
					negative_2 = ((NU8)(formatstr_p1->data[j_2]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); 						};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21);
					}
LA38_: ;
					isNumber = ((NI)0);
					{
						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < (formatstr_p1 ? formatstr_p1->Sup.len : 0));
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 							}
							T42_ = !((((NU8)(formatstr_p1->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
								if (j_2 < 0 || j_2 >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 								}
								if (!(((NU8)(formatstr_p1->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								if (nimMulInt(k, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); 								};
								if (j_2 < 0 || j_2 >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 								}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22), ((NU8)(formatstr_p1->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); 								};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); 								};
								k = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
								{
									if (!(isNumber == ((NI)0))) goto LA50_;
									isNumber = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								isNumber = ((NI)-1);
							}
LA44_: ;
							if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); 							};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25);
						} LA41: ;
					}
					{
						NI idx_2;
						if (!(isNumber == ((NI)1))) goto LA55_;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); 							};
							idx_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
						}
						goto LA57_;
LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
							if (nimSubInt(a_p2Len_0, k, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); 							};
							idx_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27);
						}
LA57_: ;
						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_u2497(formatstr_p1);
						}
LA66_: ;
						if (idx_2 < 0 || idx_2 >= a_p2Len_0){ raiseIndexError2(idx_2,a_p2Len_0-1); 						}
						unsureAsgnRef((void**) (&(*s_p0)), resizeString((*s_p0), (a_p2[idx_2] ? a_p2[idx_2]->Sup.len : 0) + 0));
appendString((*s_p0), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NI x;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
						NimStringDesc* T69_;
						if (nimAddInt(i, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); 						};
						if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); 						};
						T69_ = NIM_NIL;
						T69_ = substr__system_u9104(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31));
						x = findNormalized__pureZstrutils_u2484(T69_, a_p2, a_p2Len_0);
						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x);
							if (!(T72_)) goto LA73_;
							T72_ = (x < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); 							};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32),a_p2Len_0-1); 							}
							unsureAsgnRef((void**) (&(*s_p0)), resizeString((*s_p0), (a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)] ? a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)]->Sup.len : 0) + 0));
appendString((*s_p0), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)]);
						}
						goto LA70_;
LA74_: ;
						{
							invalidFormatString__pureZstrutils_u2497(formatstr_p1);
						}
LA70_: ;
					}
LA53_: ;
					if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); 					};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_37;
					NimStringDesc* T82_;
					if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); 					};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34);
					{
						while (1) {
							NIM_BOOL T80_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
							T80_ = (NIM_BOOL)0;
							T80_ = (j_3 < (formatstr_p1 ? formatstr_p1->Sup.len : 0));
							if (!(T80_)) goto LA81_;
							if (j_3 < 0 || j_3 >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(j_3,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 							}
							T80_ = (((NU8)(formatstr_p1->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1->data[j_3])) == ((NU8)(95)));
LA81_: ;
							if (!T80_) goto LA79;
							if (nimAddInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); 							};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
						} LA79: ;
					}
					if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); 					};
					if (nimSubInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) { raiseOverflow(); 					};
					T82_ = NIM_NIL;
					T82_ = substr__system_u9104(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37));
					x_2 = findNormalized__pureZstrutils_u2484(T82_, a_p2, a_p2Len_0);
					{
						NIM_BOOL T85_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_38;
						T85_ = (NIM_BOOL)0;
						T85_ = (((NI)0) <= x_2);
						if (!(T85_)) goto LA86_;
						T85_ = (x_2 < (a_p2Len_0-1));
LA86_: ;
						if (!T85_) goto LA87_;
						if (nimAddInt(x_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)) { raiseOverflow(); 						};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38),a_p2Len_0-1); 						}
						unsureAsgnRef((void**) (&(*s_p0)), resizeString((*s_p0), (a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)] ? a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)]->Sup.len : 0) + 0));
appendString((*s_p0), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)]);
					}
					goto LA83_;
LA87_: ;
					{
						invalidFormatString__pureZstrutils_u2497(formatstr_p1);
					}
LA83_: ;
					i = j_3;
				}
				break;
				default:
				{
					invalidFormatString__pureZstrutils_u2497(formatstr_p1);
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
				if (i < 0 || i >= (formatstr_p1 ? formatstr_p1->Sup.len : 0)){ raiseIndexError2(i,(formatstr_p1 ? formatstr_p1->Sup.len : 0)-1); 				}
				unsureAsgnRef((void**) (&(*s_p0)), addChar((*s_p0), formatstr_p1->data[i]));
				if (nimAddInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); 				};
				i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
			}
LA3_: ;
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr_p0, NimStringDesc** a_p1, NI a_p1Len_0) {
	NimStringDesc* result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
	result = NIM_NIL;
	if (nimAddInt((formatstr_p0 ? formatstr_p0->Sup.len : 0), (NI)((NU64)(a_p1Len_0) << (NU64)(((NI)4))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); 	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	result = rawNewString(((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5))));
	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	return result;
}
