/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sjson.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@sjson.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ;
typedef struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w tySequence__9cCoiKBuW1Zm17EGUhnwT1w;
typedef struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q tySequence__IfC4BMqPa86Eu3F1k8SL4Q;
typedef struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g;
typedef struct tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ;
typedef struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__zHcNN5cfKaXD6nyF1OJcyA tySequence__zHcNN5cfKaXD6nyF1OJcyA;
typedef struct Exception Exception;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag;
typedef struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw;
struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ {
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* data;
	NI counter;
	NI first;
	NI last;
};
struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw kind;
union{
struct {	NimStringDesc* str;
} _kind_1;
struct {	NI64 num;
} _kind_2;
struct {	NF fnum;
} _kind_3;
struct {	NIM_BOOL bval;
} _kind_4;
struct {	tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ fields;
} _kind_6;
struct {	tySequence__IfC4BMqPa86Eu3F1k8SL4Q* elems;
} _kind_7;
};
};
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg {
  RootObj Sup;
	NI bufpos;
	NimStringDesc* buf;
	tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg;
typedef NU8 tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw;
typedef NU8 tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA;
struct tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ {
  tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg Sup;
	NimStringDesc* a;
	tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg tok;
	tyEnum_JsonEventKind__Z0yUls5TNirubOjTqye8Cw kind;
	tyEnum_JsonError__TwbebOZrZoT9bkViQJkLnlA err;
	tySequence__zHcNN5cfKaXD6nyF1OJcyA* state;
	NimStringDesc* filename;
	NIM_BOOL rawStringLiterals;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* Field3;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
typedef N_NIMCALL_PTR(void, tyProc__vDrBeS6l6BRAY9c0GHoudsQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ttkEVvmYf0hsMP08MJMDuQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__Ae48H5ebeDGGPrl3XLNs4Q) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__CYTPrwuxH9aH4peeDNkliSw) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__ScPYATjQ5BT0khwFJ9cqRNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** buffer_p1, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__N5reTQ4MoJsyv25NbYn5uQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc** line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__9axDJsqt9cvr06KdjeoLhOMg) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ) (tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g {
  RootObj Sup;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ closeImpl;
	tyProc__ttkEVvmYf0hsMP08MJMDuQ atEndImpl;
	tyProc__Ae48H5ebeDGGPrl3XLNs4Q setPositionImpl;
	tyProc__CYTPrwuxH9aH4peeDNkliSw getPositionImpl;
	tyProc__ScPYATjQ5BT0khwFJ9cqRNQ readDataStrImpl;
	tyProc__N5reTQ4MoJsyv25NbYn5uQ readLineImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg readDataImpl;
	tyProc__9axDJsqt9cvr06KdjeoLhOMg peekDataImpl;
	tyProc__EMT9b9b1dHUNH5MLNkNSOSNQ writeDataImpl;
	tyProc__vDrBeS6l6BRAY9c0GHoudsQ flushImpl;
};
struct tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag {
  tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g Sup;
	NimStringDesc* data;
	NI pos;
};
typedef NU8 tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ;
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ {
	NI a;
	NI b;
};
struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w {
  TGenericSeq Sup;
  tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg data[SEQ_DECL_SIZE];
};
struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* data[SEQ_DECL_SIZE];
};
struct tySequence__zHcNN5cfKaXD6nyF1OJcyA {
  TGenericSeq Sup;
  tyEnum_ParserState__ZjF3gjthbAdBlIANg3rGAQ data[SEQ_DECL_SIZE];
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5502)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc* filename_p1, NIM_BOOL rawIntegers_p2, NIM_BOOL rawFloats_p3);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsejson_u79)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0, tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* input_p1, NimStringDesc* filename_p2, NIM_BOOL rawStringLiterals_p3);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg, getTok__pureZparsejson_u522)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5464)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2, NI depth_p3);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tySequence__9cCoiKBuW1Zm17EGUhnwT1w)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__IfC4BMqPa86Eu3F1k8SL4Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__jkGOOYL34s9ae9by8AteCZ2A)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f_p0, NimStringDesc* discVal_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e_p0, TNimType* typ_p1);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJRawNumber__pureZjson_u116)(NimStringDesc* s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJInt__pureZjson_u119)(NI64 n_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s_p0);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj_p0, TNimType* subclass_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJFloat__pureZjson_u122)(NF n_p0);
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJBool__pureZjson_u125)(NIM_BOOL b_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJNull__pureZjson_u128)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_u691)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, NimStringDesc* msg_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJObject__pureZjson_u130)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u132)(NI initialSize_p0, tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eat__pureZparsejson_u731)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg tok_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, X5BX5Deq___pureZjson_u2033)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* obj_p0, NimStringDesc* key_p1, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u99)(NimStringDesc* msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u369)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJArray__pureZjson_u178)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u300)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* father_p0, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* child_p1);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s_p0, TNimType* typ_p1);
static N_INLINE(void, close__pureZparsejson_u189)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_u14)(tyObject_BaseLexer__6nHBcS9cBoISVEBovO9cEAHg* L_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag*, newStringStream__pureZstreams_u749)(NimStringDesc* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u2702)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1);
extern TNimType NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_;
N_LIB_PRIVATE TNimType NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIbiggestint__Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
N_LIB_PRIVATE TNimType NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_;
N_LIB_PRIVATE TNimType NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_;
N_LIB_PRIVATE TNimType NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_;
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_8, "field \'str\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 67);
extern TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_9, "}", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_10, "string literal as key", 21);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_12, "json.nim(390, 9) `obj.kind == JObject` ", 39);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_13, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 70);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_14, "]", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_15, "json.nim(301, 3) `father.kind == JArray` ", 41);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_16, "field \'elems\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 69);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_18, "{", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_19, "input", 5);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_20, "json.nim(561, 9) `node.kind == JObject` ", 40);
TNimNode* NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[8];
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
extern NIM_THREADVAR Exception* currException__system_u2605;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_NIMCALL(void, Marker_tySequence__9cCoiKBuW1Zm17EGUhnwT1w)(void* p, NI op) {
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* a;
	NI T1_;
	a = (tySequence__9cCoiKBuW1Zm17EGUhnwT1w*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__IfC4BMqPa86Eu3F1k8SL4Q)(void* p, NI op) {
	tySequence__IfC4BMqPa86Eu3F1k8SL4Q* a;
	NI T1_;
	a = (tySequence__IfC4BMqPa86Eu3F1k8SL4Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef__jkGOOYL34s9ae9by8AteCZ2A)(void* p, NI op) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* a;
	a = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*)p;
	switch ((*a).kind) {
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)4):
	nimGCvisit((void*)(*a)._kind_1.str, op);
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)2):
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)3):
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)1):
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)0):
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)5):
	nimGCvisit((void*)(*a)._kind_6.fields.data, op);
	break;
	case ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)6):
	nimGCvisit((void*)(*a)._kind_7.elems, op);
	break;
	} 
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u6026(p_p0);
	decRef__system_u6071(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJRawNumber__pureZjson_u116)(NimStringDesc* s_p0) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	NimStringDesc* T2_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)4);
	T2_ = NIM_NIL;
	T2_ = (*T1_)._kind_1.str; (*T1_)._kind_1.str = copyStringRC1(s_p0);
	if (T2_) nimGCunrefNoCycle(T2_);
	(*T1_).isUnquoted = NIM_TRUE;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJInt__pureZjson_u119)(NI64 n_p0) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)2);
	(*T1_)._kind_2.num = n_p0;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_u2605;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_u2605), (*currException__system_u2605).up);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJFloat__pureZjson_u122)(NF n_p0) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)3);
	(*T1_)._kind_3.fnum = n_p0;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJBool__pureZjson_u125)(NIM_BOOL b_p0) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)1);
	(*T1_)._kind_4.bval = b_p0;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJNull__pureZjson_u128)(void) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)0);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJObject__pureZjson_u130)(void) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)5);
	initOrderedTable__pureZjson_u132(((NI)2), (&(*T1_)._kind_6.fields));
	result = T1_;
	return result;
}
static N_INLINE(void, X5BX5Deq___pureZjson_u2033)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* obj_p0, NimStringDesc* key_p1, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val_p2) {
	{
		if (!!(((*obj_p0).kind == ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)5)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_12));
	}
LA3_: ;
	if (!(((32 &((NU8)1<<((NU)(((*obj_p0).kind))&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_13), reprDiscriminant(((NI)((*obj_p0).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 	}
	X5BX5Deq___pureZjson_u369((&(*obj_p0)._kind_6.fields), key_p1, val_p2);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, newJArray__pureZjson_u178)(void) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
	(*T1_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)6);
	if ((*T1_)._kind_7.elems) { nimGCunrefNoCycle((*T1_)._kind_7.elems); (*T1_)._kind_7.elems = NIM_NIL; }
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u300)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* father_p0, tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* child_p1) {
	NI T5_;
	{
		if (!!(((*father_p0).kind == ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)6)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_15));
	}
LA3_: ;
	if (!(((64 &((NU8)1<<((NU)(((*father_p0).kind))&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)((*father_p0).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 	}
	asgnRef((void**) (&(*father_p0)._kind_7.elems), (tySequence__IfC4BMqPa86Eu3F1k8SL4Q*) incrSeqV3((TGenericSeq*)((*father_p0)._kind_7.elems), (&NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_)));
	T5_ = (*father_p0)._kind_7.elems->Sup.len++;
	asgnRef((void**) (&(*father_p0)._kind_7.elems->data[T5_]), child_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5464)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* p_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2, NI depth_p3) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	result = NIM_NIL;
	switch ((*p_p0).tok) {
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)2):
	{
		tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T2_;
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T3_;
		T2_ = NIM_NIL;
		T2_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*) newObj((&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_), sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA));
		(*T2_).kind = ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)4);
		asgnRef((void**) (&(*T2_)._kind_1.str), NIM_NIL);
		result = T2_;
		if (!(((16 &((NU8)1<<((NU)(((*result).kind))&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_8), reprDiscriminant(((NI)((*result).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 		}
		asgnRef((void**) (&(*result)._kind_1.str), (*p_p0).a);
		unsureAsgnRef((void**) (&(*p_p0).a), ((NimStringDesc*) NIM_NIL));
		T3_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T3_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T3_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)3):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T13_;
		{
			if (!rawIntegers_p1) goto LA7_;
			result = newJRawNumber__pureZjson_u116((*p_p0).a);
		}
		goto LA5_;
LA7_: ;
		{
			NI64 T10_;
			T10_ = (NI64)0;
			T10_ = nsuParseBiggestInt((*p_p0).a);
			result = newJInt__pureZjson_u119(T10_);
			if (nimBorrowCurrentException()) {
				if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_))) {
					result = newJRawNumber__pureZjson_u116((*p_p0).a);
					popCurrentException();
				}
			}
		}
LA5_: ;
		T13_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T13_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T13_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)4):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T23_;
		{
			if (!rawFloats_p2) goto LA17_;
			result = newJRawNumber__pureZjson_u116((*p_p0).a);
		}
		goto LA15_;
LA17_: ;
		{
			NF T20_;
			T20_ = (NF)0;
			T20_ = nsuParseFloat((*p_p0).a);
			result = newJFloat__pureZjson_u122(T20_);
			if (nimBorrowCurrentException()) {
				if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_))) {
					result = newJRawNumber__pureZjson_u116((*p_p0).a);
					popCurrentException();
				}
			}
		}
LA15_: ;
		T23_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T23_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T23_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)5):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T25_;
		result = newJBool__pureZjson_u125(NIM_TRUE);
		T25_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T25_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T25_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)6):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T27_;
		result = newJBool__pureZjson_u125(NIM_FALSE);
		T27_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T27_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T27_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)7):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T29_;
		result = newJNull__pureZjson_u128();
		T29_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T29_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T29_);
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)8):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T35_;
		{
			if (!(((NI)1000) < depth_p3)) goto LA33_;
			raiseParseErr__pureZparsejson_u691((&(*p_p0)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_9));
		}
LA33_: ;
		result = newJObject__pureZjson_u130();
		T35_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T35_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T35_);
		{
			while (1) {
				NimStringDesc* key;
				tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T42_;
				tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* val;
				NI TM__9b9bytt1stv9cZ8uqII7HFgew_11;
				tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T47_;
				if (!!(((*p_p0).tok == ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)9)))) goto LA37;
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)2)))) goto LA40_;
					raiseParseErr__pureZparsejson_u691((&(*p_p0)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_10));
				}
LA40_: ;
				key = copyString((*p_p0).a);
				T42_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
				T42_ = getTok__pureZparsejson_u522(p_p0);
				(void)(T42_);
				eat__pureZparsejson_u731(p_p0, ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)12));
				if (nimAddInt(depth_p3, ((NI)1), &TM__9b9bytt1stv9cZ8uqII7HFgew_11)) { raiseOverflow(); 				};
				val = parseJson__pureZjson_u5464(p_p0, rawIntegers_p1, rawFloats_p2, (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_11));
				X5BX5Deq___pureZjson_u2033(result, key, val);
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)13)))) goto LA45_;
					goto LA36;
				}
LA45_: ;
				T47_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
				T47_ = getTok__pureZparsejson_u522(p_p0);
				(void)(T47_);
			} LA37: ;
		} LA36: ;
		eat__pureZparsejson_u731(p_p0, ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)9));
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)10):
	{
		tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T53_;
		{
			if (!(((NI)1000) < depth_p3)) goto LA51_;
			raiseParseErr__pureZparsejson_u691((&(*p_p0)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_14));
		}
LA51_: ;
		result = newJArray__pureZjson_u178();
		T53_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
		T53_ = getTok__pureZparsejson_u522(p_p0);
		(void)(T53_);
		{
			while (1) {
				NI TM__9b9bytt1stv9cZ8uqII7HFgew_17;
				tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T56_;
				tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T61_;
				if (!!(((*p_p0).tok == ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)11)))) goto LA55;
				if (nimAddInt(depth_p3, ((NI)1), &TM__9b9bytt1stv9cZ8uqII7HFgew_17)) { raiseOverflow(); 				};
				T56_ = NIM_NIL;
				T56_ = parseJson__pureZjson_u5464(p_p0, rawIntegers_p1, rawFloats_p2, (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_17));
				add__pureZjson_u300(result, T56_);
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)13)))) goto LA59_;
					goto LA54;
				}
LA59_: ;
				T61_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
				T61_ = getTok__pureZparsejson_u522(p_p0);
				(void)(T61_);
			} LA55: ;
		} LA54: ;
		eat__pureZparsejson_u731(p_p0, ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)11));
	}
	break;
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0):
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)9):
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)11):
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)12):
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)13):
	case ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)1):
	{
		raiseParseErr__pureZparsejson_u691((&(*p_p0)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_18));
	}
	break;
	}
	return result;
}
static N_INLINE(void, close__pureZparsejson_u189)(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ* my_p0) {
	close__pureZlexbase_u14(&my_p0->Sup);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5502)(tyObject_StreamObj__hNmHk9a6m386ZI9c8umyup7g* s_p0, NimStringDesc* filename_p1, NIM_BOOL rawIntegers_p2, NIM_BOOL rawFloats_p3) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ p;
	tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg T1_;
	result = NIM_NIL;
	nimZeroMem((void*)(&p), sizeof(tyObject_JsonParser__bHG1u6i3QKCuUHQgaTxScQ));
	p.Sup.Sup.m_type = (&NTIjsonparser__bHG1u6i3QKCuUHQgaTxScQ_);
	open__pureZparsejson_u79((&p), s_p0, filename_p1, NIM_FALSE);
	T1_ = (tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)0;
	T1_ = getTok__pureZparsejson_u522((&p));
	(void)(T1_);
	result = parseJson__pureZjson_u5464((&p), rawIntegers_p2, rawFloats_p3, ((NI)0));
	eat__pureZparsejson_u731((&p), ((tyEnum_TokKind__7uWPm2TEolRM1uqyBZh9asg)1));
	{
	}
	{
		close__pureZparsejson_u189((&p));
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5509)(NimStringDesc* buffer_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_StringStreamObj__2VWq9a8gmGbkj9bGsucBK1ag* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = newStringStream__pureZstreams_u749(buffer_p0);
	result = parseJson__pureZjson_u5502(&T1_->Sup, ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_19), rawIntegers_p1, rawFloats_p2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3369)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* node_p0, NimStringDesc* key_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!(((*node_p0).kind == ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)5)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_20));
	}
LA3_: ;
	if (!(((32 &((NU8)1<<((NU)(((*node_p0).kind))&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_13), reprDiscriminant(((NI)((*node_p0).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 	}
	result = hasKey__pureZjson_u2702((&(*node_p0)._kind_6.fields), key_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr__pureZjson_u216)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* n_p0, NimStringDesc* default_p1) {
	NimStringDesc* result;
{	result = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)4)));
LA4_: ;
		if (!T3_) goto LA5_;
		result = copyString(default_p1);
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		if (!(((16 &((NU8)1<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_8), reprDiscriminant(((NI)((*n_p0).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 		}
		result = copyString((*n_p0)._kind_1.str);
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsjsondotnim_DatInit000)(void) {
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_2_2[2];
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_3_7[7];
NI TM__9b9bytt1stv9cZ8uqII7HFgew_5;
static char* NIM_CONST TM__9b9bytt1stv9cZ8uqII7HFgew_4[7] = {
"JNull", 
"JBool", 
"JInt", 
"JFloat", 
"JString", 
"JObject", 
"JArray"};
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[4];
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[4];
static TNimNode TM__9b9bytt1stv9cZ8uqII7HFgew_0[28];
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.size = sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA);
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.align = NIM_ALIGNOF(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA);
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.kind = 18;
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.base = 0;
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.flags = 2;
TM__9b9bytt1stv9cZ8uqII7HFgew_2_2[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[1];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, isUnquoted);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].name = "isUnquoted";
TM__9b9bytt1stv9cZ8uqII7HFgew_2_2[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[2];
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.size = sizeof(tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw);
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.align = NIM_ALIGNOF(tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw);
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.kind = 14;
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.base = 0;
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.flags = 3;
for (TM__9b9bytt1stv9cZ8uqII7HFgew_5 = 0; TM__9b9bytt1stv9cZ8uqII7HFgew_5 < 7; TM__9b9bytt1stv9cZ8uqII7HFgew_5++) {
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_5+3].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_5+3].offset = TM__9b9bytt1stv9cZ8uqII7HFgew_5;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_5+3].name = TM__9b9bytt1stv9cZ8uqII7HFgew_4[TM__9b9bytt1stv9cZ8uqII7HFgew_5];
TM__9b9bytt1stv9cZ8uqII7HFgew_3_7[TM__9b9bytt1stv9cZ8uqII7HFgew_5] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_5+3];
}
TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].len = 7; TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_3_7[0];
NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[10];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].kind = 3;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, kind);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].typ = (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].name = "kind";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].sons = &NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[0];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].len = 7;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_1.str);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].name = "str";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[4] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[11];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_2.num);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].typ = (&NTIbiggestint__Aav8dQoMlCFnZRxA0IhTHQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].name = "num";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[12];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_3.fnum);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].typ = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].name = "fnum";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[13];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_4.bval);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].name = "bval";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[14];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[15].len = 0; TM__9b9bytt1stv9cZ8uqII7HFgew_0[15].kind = 2;
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[15];
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.size = sizeof(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ);
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.align = NIM_ALIGNOF(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ);
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.kind = 18;
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.base = 0;
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.flags = 2;
TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[18];
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.size = sizeof(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg);
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.align = NIM_ALIGNOF(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg);
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.kind = 18;
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.base = 0;
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.flags = 2;
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[20];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].offset = offsetof(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg, Field0);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].name = "Field0";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[21];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].offset = offsetof(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg, Field1);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].name = "Field1";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[22];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].offset = offsetof(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg, Field2);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].name = "Field2";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[23];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].offset = offsetof(tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg, Field3);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].typ = (&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].name = "Field3";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].len = 4; TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[0];
NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[19];
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.size = sizeof(tySequence__9cCoiKBuW1Zm17EGUhnwT1w*);
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.align = NIM_ALIGNOF(tySequence__9cCoiKBuW1Zm17EGUhnwT1w*);
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.kind = 24;
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.base = (&NTIorderedkeyvaluepair__E9a9bFH6Zoc2g4QB9cAeG9brEg_);
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.flags = 2;
NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_.marker = Marker_tySequence__9cCoiKBuW1Zm17EGUhnwT1w;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].offset = offsetof(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ, data);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].typ = (&NTIorderedkeyvaluepairseq__9cCoiKBuW1Zm17EGUhnwT1w_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].name = "data";
TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[24];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].offset = offsetof(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ, counter);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].name = "counter";
TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[25];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].offset = offsetof(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ, first);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].name = "first";
TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[26];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].offset = offsetof(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ, last);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].name = "last";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].len = 4; TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_6_4[0];
NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[17];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_6.fields);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].typ = (&NTIorderedtable__9cf9bkGxLWl0yGAOn35lDueQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].name = "fields";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[5] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[16];
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.size = sizeof(tySequence__IfC4BMqPa86Eu3F1k8SL4Q*);
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.align = NIM_ALIGNOF(tySequence__IfC4BMqPa86Eu3F1k8SL4Q*);
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.kind = 24;
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.base = (&NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_);
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.flags = 2;
NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_.marker = Marker_tySequence__IfC4BMqPa86Eu3F1k8SL4Q;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].offset = offsetof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA, _kind_7.elems);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].typ = (&NTIseqLjsonnodeT__IfC4BMqPa86Eu3F1k8SL4Q_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].name = "elems";
NimDT___H5PcDYRCt0M9aMlAwGM9crJA_kind[6] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[27];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].len = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_2_2[0];
NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[0];
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.size = sizeof(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*);
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.align = NIM_ALIGNOF(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*);
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.kind = 22;
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.base = (&NTIjsonnodeobj__H5PcDYRCt0M9aMlAwGM9crJA_);
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.flags = 2;
NTIjsonnode__jkGOOYL34s9ae9by8AteCZ2A_.marker = Marker_tyRef__jkGOOYL34s9ae9by8AteCZ2A;
}

