/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@sstd@sassertions.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@sstd@sassertions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u48)(NimStringDesc* msg_p0);
static N_INLINE(void, sysFatal__stdZassertions_u50)(NimStringDesc* message_p1);
static N_INLINE(void, sysFatal__stdZassertions_u54)(NimStringDesc* message_p1, NimStringDesc* arg_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace__system_u2200)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap_p0);
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest_p0, NI addlen_p1);
static N_INLINE(void, rawWrite)(FILE* f_p0, NCSTRING s_p1);
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0);
STRING_LITERAL(TM__h1bPSEm4o1Lcq1L2w1tzIQ_2, "Error: unhandled exception: ", 28);
STRING_LITERAL(TM__h1bPSEm4o1Lcq1L2w1tzIQ_3, " [", 2);
STRING_LITERAL(TM__h1bPSEm4o1Lcq1L2w1tzIQ_4, "AssertionDefect", 15);
STRING_LITERAL(TM__h1bPSEm4o1Lcq1L2w1tzIQ_5, "]\012", 2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringDesc* dest_p0, NimStringDesc* src_p1) {
	{
		if (!!((src_p1 == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_u1759(((void*) ((&(*dest_p0).data[(*dest_p0).Sup.len]))), ((void*) ((*src_p1).data)), ((NI) ((NI)((*src_p1).Sup.len + ((NI)1)))));
		(*dest_p0).Sup.len += (*src_p1).Sup.len;
	}
LA3_: ;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a_p0);
	result = ((NI) (T1_));
	return result;
}
static N_INLINE(void, rawWrite)(FILE* f_p0, NCSTRING s_p1) {
	size_t T1_;
	int T2_;
	T1_ = (size_t)0;
	T1_ = fwrite(((void*) (s_p1)), ((size_t)1), ((size_t) ((s_p1 ? nimCStrLen(s_p1) : 0))), f_p0);
	(void)(T1_);
	T2_ = (int)0;
	T2_ = fflush(f_p0);
	(void)(T2_);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s_p0 == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s_p0).Sup.len == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
LA5_: ;
	{
		result = ((NCSTRING) ((*s_p0).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, sysFatal__stdZassertions_u54)(NimStringDesc* message_p1, NimStringDesc* arg_p2) {
	NimStringDesc* buf;
	writeStackTrace__system_u2200();
	buf = rawNewString(((NI)200));
	buf = resizeString(buf, 28);
appendString(buf, ((NimStringDesc*) &TM__h1bPSEm4o1Lcq1L2w1tzIQ_2));
	buf = resizeString(buf, (message_p1 ? message_p1->Sup.len : 0) + 0);
appendString(buf, message_p1);
	buf = resizeString(buf, (arg_p2 ? arg_p2->Sup.len : 0) + 0);
appendString(buf, arg_p2);
	buf = resizeString(buf, 2);
appendString(buf, ((NimStringDesc*) &TM__h1bPSEm4o1Lcq1L2w1tzIQ_3));
	buf = resizeString(buf, 15);
appendString(buf, ((NimStringDesc*) &TM__h1bPSEm4o1Lcq1L2w1tzIQ_4));
	buf = resizeString(buf, 2);
appendString(buf, ((NimStringDesc*) &TM__h1bPSEm4o1Lcq1L2w1tzIQ_5));
	rawWrite(stderr, nimToCStringConv(buf));
	exit(((int)1));
}
static N_INLINE(void, sysFatal__stdZassertions_u50)(NimStringDesc* message_p1) {
	sysFatal__stdZassertions_u54(message_p1, ((NimStringDesc*) NIM_NIL));
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u48)(NimStringDesc* msg_p0) {
	sysFatal__stdZassertions_u50(msg_p0);
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u99)(NimStringDesc* msg_p0) {
	raiseAssert__stdZassertions_u48(msg_p0);
}
