/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@scollections@ssharedlist.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.0.0@slib@spure@scollections@ssharedlist.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
typedef void* tyArray__Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* next;
	NI dataLen;
	tyArray__Rrw59cMvNu8cDA9cQDh4v2oA d;
};
typedef int tyArray__Pk9c8DhUOqt8r9aBvHyrLtnw[1];
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0);
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0) {
	pthread_mutex_init(lock_p0, ((pthread_mutexattr_t*) NIM_NIL));
}
N_LIB_PRIVATE N_NIMCALL(void, init__system_u6397)(tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw* t_p0) {
	initLock__coreZlocks_u7((&(*t_p0).lock));
	(*t_p0).head = ((tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg*) NIM_NIL);
	(*t_p0).tail = ((tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg*) NIM_NIL);
}
