/* Generated by Nim Compiler v2.0.0 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread -O3 -fno-strict-aliasing -fno-ident -fno-math-errno  -fPIC  -I/home/issam/.choosenim/toolchains/nim-2.0.0/lib -I/home/issam/Desktop/workspace/tests/nim-call-c -o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@me.nim.c.o /home/issam/Desktop/workspace/tests/nim-call-c/libsrc/@me.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA;
typedef struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ;
typedef struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w tySequence__9cCoiKBuW1Zm17EGUhnwT1w;
typedef struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q tySequence__IfC4BMqPa86Eu3F1k8SL4Q;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
typedef struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw;
struct tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ {
	tySequence__9cCoiKBuW1Zm17EGUhnwT1w* data;
	NI counter;
	NI first;
	NI last;
};
struct tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw kind;
union{
struct {	NimStringDesc* str;
} _kind_1;
struct {	NI64 num;
} _kind_2;
struct {	NF fnum;
} _kind_3;
struct {	NIM_BOOL bval;
} _kind_4;
struct {	tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ fields;
} _kind_6;
struct {	tySequence__IfC4BMqPa86Eu3F1k8SL4Q* elems;
} _kind_7;
};
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	pthread_mutex_t lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* Field3;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
struct tySequence__9cCoiKBuW1Zm17EGUhnwT1w {
  TGenericSeq Sup;
  tyTuple__E9a9bFH6Zoc2g4QB9cAeG9brEg data[SEQ_DECL_SIZE];
};
struct tySequence__IfC4BMqPa86Eu3F1k8SL4Q {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* data[SEQ_DECL_SIZE];
};
N_LIB_EXPORT N_CDECL(int, add)(int x_p0, int y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(void, printNameFromJson)(NCSTRING s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, parseJson__pureZjson_u5509)(NimStringDesc* buffer_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3369)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* node_p0, NimStringDesc* key_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr__pureZjson_u216)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* n_p0, NimStringDesc* default_p1);
static N_INLINE(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, X5BX5D___pureZjson_u3252)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* node_p0, NimStringDesc* name_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u99)(NimStringDesc* msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA**, X5BX5D___pureZjson_u2776)(tyObject_OrderedTable__9cf9bkGxLWl0yGAOn35lDueQ* t_p0, NimStringDesc* key_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f_p0, NimStringDesc* discVal_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e_p0, TNimType* typ_p1);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args_p0, NI args_p0Len_0);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj_p0, TNimType* subclass_p1);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u6020)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, TM__56TX8Bu5PD5fXC6a9cMUatQ_9)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0);
static N_INLINE(void, initStackBottomWith)(void* locals_p0);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom_p0);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsexceptionsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsctypesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsstreamsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatslexbasedotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsparsejsondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsjsondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_3, "name", 4);
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_4, "json.nim(514, 9) `not isNil(node)` ", 35);
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_5, "json.nim(515, 9) `node.kind == JObject` ", 40);
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_6, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 70);
extern TNimType NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_;
extern TNimType NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_;
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_8, "Invalid JSON", 12);
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
STRING_LITERAL(TM__56TX8Bu5PD5fXC6a9cMUatQ_10, "{\"name\":\"Issa\303\271\",\"age\":30,\"languages\":[\"Nim\",\"Python\",\"C\"]}", 59);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__56TX8Bu5PD5fXC6a9cMUatQ_7 = {((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_8)}
;
extern NIM_THREADVAR Exception* currException__system_u2605;
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5959;
N_LIB_PRIVATE NimStringDesc* jsonStr__e_u9;
N_LIB_EXPORT N_CDECL(int, add)(int x_p0, int y_p1) {
	int result;
	NI TM__56TX8Bu5PD5fXC6a9cMUatQ_2;
{	result = (int)0;
	if (nimAddInt(x_p0, y_p1, &TM__56TX8Bu5PD5fXC6a9cMUatQ_2)) { raiseOverflow(); 	};
	if (TM__56TX8Bu5PD5fXC6a9cMUatQ_2 < (-2147483647 -1) || TM__56TX8Bu5PD5fXC6a9cMUatQ_2 > 2147483647){ raiseOverflow(); 	}
	result = (NI32)(TM__56TX8Bu5PD5fXC6a9cMUatQ_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA*, X5BX5D___pureZjson_u3252)(tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* node_p0, NimStringDesc* name_p1) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* result;
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA** T9_;
	result = NIM_NIL;
	{
		if (!!(!((node_p0 == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_4));
	}
LA3_: ;
	{
		if (!!(((*node_p0).kind == ((tyEnum_JsonNodeKind__tKTWYTxDOnJpnaoV9brS9c9bw)5)))) goto LA7_;
		failedAssertImpl__stdZassertions_u99(((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_5));
	}
LA7_: ;
	if (!(((32 &((NU8)1<<((NU)(((*node_p0).kind))&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_6), reprDiscriminant(((NI)((*node_p0).kind)) + (NI)IL64(0), (&NTIjsonnodekind__tKTWYTxDOnJpnaoV9brS9c9bw_))); 	}
	T9_ = (tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA**)0;
	T9_ = X5BX5D___pureZjson_u2776((&(*node_p0)._kind_6.fields), name_p1);
	result = (*T9_);
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_u2605;
	return result;
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6064)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u6026)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6069)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u6020((&gch__system_u5959.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6071)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6069(c_p0);
	}
LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u6026(src_p1);
		incRef__system_u6064(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u6026((*dest_p0));
		decRef__system_u6071(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_u2605), (*currException__system_u2605).up);
}
N_LIB_EXPORT N_CDECL(void, printNameFromJson)(NCSTRING s_p0) {
	tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* obj;
	NimStringDesc* T1_;
	T1_ = NIM_NIL;
	T1_ = cstrToNimstr(s_p0);
	obj = parseJson__pureZjson_u5509(T1_, NIM_FALSE, NIM_FALSE);
	{
		NIM_BOOL T4_;
		tyArray__nHXaesL0DJZHyVS07ARPRA T7_;
		tyObject_JsonNodeObj__H5PcDYRCt0M9aMlAwGM9crJA* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = hasKey__pureZjson_u3369(obj, ((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_3));
		if (!T4_) goto LA5_;
		nimZeroMem((void*)T7_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T8_ = NIM_NIL;
		T8_ = X5BX5D___pureZjson_u3252(obj, ((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_3));
		T7_[0] = getStr__pureZjson_u216(T8_, ((NimStringDesc*) NIM_NIL));
		echoBinSafe(T7_, 1);
	}
LA5_: ;
	if (nimBorrowCurrentException()) {
		if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIjsonparsingerror__Gif6MC6XqT1zppIkieVG6g_))) {
			echoBinSafe(TM__56TX8Bu5PD5fXC6a9cMUatQ_7, 1);
			popCurrentException();
		}
	}
}
static N_NIMCALL(void, TM__56TX8Bu5PD5fXC6a9cMUatQ_9)(void) {
	nimGCvisit((void*)jsonStr__e_u9, 0);
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u6026(p_p0);
	decRef__system_u6071(T1_);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s_p0 == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s_p0).Sup.len == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
LA5_: ;
	{
		result = ((NCSTRING) ((*s_p0).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, initStackBottomWith)(void* locals_p0) {
	nimGC_setStackBottom(locals_p0);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 1
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsexceptionsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsctypesdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsstreamsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatslexbasedotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsparsejsondotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsjsondotnim_DatInit000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsexceptionsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsctypesdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsstreamsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatslexbasedotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsparsejsondotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatspureatsjsondotnim_DatInit000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 1
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
#else
	PreMain();
	initStackBottomWith((void *)&inner);
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__56TX8Bu5PD5fXC6a9cMUatQ_9);

}/* preInitProc end */
{
	NimStringDesc* T1_;
	T1_ = NIM_NIL;
	T1_ = jsonStr__e_u9; jsonStr__e_u9 = copyStringRC1(((NimStringDesc*) &TM__56TX8Bu5PD5fXC6a9cMUatQ_10));
	if (T1_) nimGCunrefNoCycle(T1_);
	printNameFromJson(nimToCStringConv(jsonStr__e_u9));
}
}

